const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const questions = [
  {
    "exam": "CUET",
    "questionId": "1",
    "text": "The compound is\n(1) Antiseptic\n(2) Antibiotic\n(3) Analgesic\n(4) Pesticide",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Applications of Aspirin",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Antiseptic", "Antibiotic", "Analgesic", "Pesticide"],
    "correctOption": "3",
    "markscheme": "The given compound is \"Aspirin (Salicylic acid), which is used for the treatment of fever and mild pain.\"",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "2",
    "text": "A small amount of \\(\\mathrm{CaF}_{2}\\) is added in electrolytic reduction of \\(\\mathrm{Al}_{2} \\mathrm{O}_{3}\\) dissolved in fused cryolite\n\n(A) To decrease the rate of oxidation of carbon at anode\n\n(B) To act as catalyst\n\n(C) To make fused mixture conducting\n\n(D) To lower the fusion temperature of melting\n\nChoose the correct answer from the options given below:\n(1) (A), (B), (D) only\n(2) (B), (C) only\n(3) (A), (B) only\n(4) (C), (D) only",
    "subject": "Chemistry",
    "topic": "Inorganic Chemistry",
    "subtopic": "Electrolytic Reduction",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["(A), (B), (D) only", "(B), (C) only", "(A), (B) only", "(C), (D) only"],
    "correctOption": "4",
    "markscheme": "A small amount of \\(\\mathrm{CaF}_{2}\\) is added in electrolytic reduction of \\(\\mathrm{Al}_{2} \\mathrm{O}_{3}\\) dissolved in fused cryolite because it enhance the electrical conductivity of fused mixture of \\(\\mathrm{Al}_{2} \\mathrm{O}_{3}\\) and it lowers the fusion temperature of melting.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "3",
    "text": "Match List -I with List - II.\n\n\\begin{tabular}{|c|c|c|c|}\n\\hline & \\begin{tabular}{l} \nList -1 \\\\ Complex\n\\end{tabular} & & \\begin{tabular}{l} \nList - II \\\\ hybridisation\n\\end{tabular} \\\\ \\hline \\begin{tabular}{l} \n(A) \\\\ (B) \\\\ (C) \\\\ (D)\n\\end{tabular} & ![](https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-01.jpg?height=149\\&width=185\\&top_left_y=2444\\&top_left_x=357) & \\begin{tabular}{l} \n(I) \\\\ (II) \\\\ (III) \\\\ (IV)\n\\end{tabular} & \\begin{tabular}{l}\n\\(\\mathrm{sp}^{3}\\) \\\\ \\(\\mathrm{dsp}^{2}\\) \\\\ \\(\\mathrm{d}^{2} \\mathrm{sp}^{3}\\) \\\\ \\(\\mathrm{sp}^{3} \\mathrm{d}^{2}\\)\n\\end{tabular} \\\\ \\hline\n\\end{tabular}\n\nChoose the correct answer from the options given below\n\n(1) (A)-(I), (B)-(II), (C)-(III), (D)-(IV)\n\n(2) (A)-(II), (B)-(III), (C)-(IV), (D)-(I)\n\n(3) (A)-(III), (B)-(IV), (C)-(I), (D)-(II)\n\n(4) (A)-(IV), (B)-(III), (C)-(I), (D)-(II)",
    "subject": "Chemistry",
    "topic": "Coordination Chemistry",
    "subtopic": "Hybridisation in Complexes",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A)-(I), (B)-(II), (C)-(III), (D)-(IV)",
      "(A)-(II), (B)-(III), (C)-(IV), (D)-(I)",
      "(A)-(III), (B)-(IV), (C)-(I), (D)-(II)",
      "(A)-(IV), (B)-(III), (C)-(I), (D)-(II)"
    ],
    "correctOption": "4",
    "markscheme": "Hybridisation is a concept of intermixing of two atomic orbitals which give rise to a new atomic orbital and define the geometry of the complex compounds.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-01.jpg?height=149&width=185&top_left_y=2444&top_left_x=357"
  },
  {
    "exam": "CUET",
    "questionId": "4",
    "text": "Match List -I with List - II.\n\n\\begin{tabular}{|ll|ll|}\n\\hline \\multicolumn{2}{|c|}{ List -I } & \\multicolumn{2}{c|}{ List - II } \\\\\n\\hline (A) & Chloroxylenol + terpineol & (I) & Tranquillizer \\\\\n(B) & Penicillin & (II) & Analgesic \\\\\n(C) & Iproniazid & (III) & Antiseptic \\\\\n(D) & Aspirin & (IV) & Antibiotic \\\\\n\\hline\n\\end{tabular}\n\nChoose the correct answer from die options given below\n\n(1) (A)-(III), (B)-(II), (C)-(I), (D)-(IV)\n\n(2) (A)-(III), (B)-(IV), (C)-(I), (D)-(II)\n\n(3) (A)-(II), (B)-(IV), (C)-(III), (D)-(I)\n\n(4) (A)-(I), (B)-(III), (C)-(II), (D)-(IV)",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Applications of Organic Compounds",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A)-(III), (B)-(II), (C)-(I), (D)-(IV)",
      "(A)-(III), (B)-(IV), (C)-(I), (D)-(II)",
      "(A)-(II), (B)-(IV), (C)-(III), (D)-(I)",
      "(A)-(I), (B)-(III), (C)-(II), (D)-(IV)"
    ],
    "correctOption": "2",
    "markscheme": "Mixture of Chloroxylenol and terpineol is called Dettol which is used as an antiseptic. Penicillin act as antibiotic which kill/ inhibit the growth of microorganism.Iproniazid act as Tranquillizer which was initially used for treatment of Tuberculosis and later on, used as antidepressant. Aspirin used for relieving mild pain and fever.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "5",
    "text": "Zone refining is mainly used for:\n(1) Ni\n(2) Ga\n(3) Zr\n(4) Ta",
    "subject": "Chemistry",
    "topic": "Metallurgy",
    "subtopic": "Refining Methods",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Ni", "Ga", "Zr", "Ta"],
    "correctOption": "2",
    "markscheme": "Zone refining method is used for purification of metals like \\(\\mathrm{Ga}, \\mathrm{Si}\\) and Ge, which acts as semiconductors.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "6",
    "text": "An aqueous solution of \\(2 \\%\\) non-volatile solute exerts a pressure of 1.004 bar at the normal boiling point of the solvent. What is the molecular mass of the solute?\n(1) \\(41.35 \\mathrm{~g} / \\mathrm{mol}\\)\n(2) \\(10 \\mathrm{~g} / \\mathrm{mol}\\)\n(3) \\(23.4 \\mathrm{~g} / \\mathrm{mol}\\)\n(4) \\(20.8 \\mathrm{~g} / \\mathrm{mol}\\)",
    "subject": "Chemistry",
    "topic": "Solutions",
    "subtopic": "Raoult's Law",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["41.35 g/mol", "10 g/mol", "23.4 g/mol", "20.8 g/mol"],
    "correctOption": "1",
    "markscheme": "Mass of Solute \\(\\left(\\mathrm{w}_{2}\\right)=2 \\mathrm{~g}\\)\n\\begin{array}{r}\n\\text { Mass of solution }=100 \\mathrm{~g} \\\\\n\\text { Mass of solvent }=100-2 \\\\\n=98 \\mathrm{~g}\n\\end{array}\n\nvapour pressure of pure water \\(=1 \\mathrm{~atm}\\). or 1.013 bar According to Raoult's Law-\n\n\\begin{aligned}\n& \\frac{\\mathrm{P}^{\\circ}-\\mathrm{P}}{\\mathrm{P}^{\\circ}}=\\mathrm{X}_{2}=\\frac{\\mathrm{W}_{2} \\times \\mathrm{M}_{1}}{\\mathrm{M}_{2} \\times \\mathrm{W}_{1}} \\\\\n& \\frac{1.013-1.004}{1.013}=\\frac{2 \\times 18}{\\mathrm{M}_{2} \\times 98} \\\\\n& \\mathrm{M}_{2}=41.35 \\mathrm{~g} / \\mathrm{mol}\n\\end{aligned}",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "7",
    "text": "Solution of \\(\\mathrm{KMnO}_{4}\\) is reduced to various products \\(\\mathbb{P},(\\mathrm{Q}),(R\\) depending upon the pH of the solution. At \\(\\mathrm{pH}<7\\) it is reduced to colourless substance \\(\\mathbb{P}\\). At \\(\\mathrm{pH}=7\\) it forms a brown precipitate (Q) At \\(\\mathrm{pH}>7\\) it forms a green coloured solution \\(\\mathbb{R}\\).\n\n\\(\\mathbb{P}, \\mathbb{Q}), \\mathbb{R}\\), will be:\n\n\\begin{tabular}{llll} \n& \\(\\mathbb{P}\\) & \\(\\mathbb{Q}\\) & \\(\\mathbb{B}\\) \\\\\n(1) & \\(\\mathrm{Mn}^{2+}\\) & \\(\\mathrm{MnO}_{2}\\) & \\(\\mathrm{MnO}_{4}^{2-}\\) \\\\\n(2) & \\(\\mathrm{MnO}_{2}\\) & \\(\\mathrm{MnO}_{4}^{2-}\\) & \\(\\mathrm{Mn}^{2+}\\) \\\\\n(3) & \\(\\mathrm{MnO}_{4}^{2-}\\) & \\(\\mathrm{Mn}^{2+}\\) & \\(\\mathrm{MnO}_{2}\\) \\\\\n(4) & \\(\\mathrm{Mn}^{2+}\\) & \\(\\mathrm{Mn}^{4+}\\) & \\(\\mathrm{MnO}_{2}\\)\n\\end{tabular}",
    "subject": "Chemistry",
    "topic": "Redox Reactions",
    "subtopic": "Products of Reduction",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "\\(\\mathrm{Mn}^{2+}\\), \\(\\mathrm{MnO}_{2}\\), \\(\\mathrm{MnO}_{4}^{2-}\\)",
      "\\(\\mathrm{MnO}_{2}\\), \\(\\mathrm{MnO}_{4}^{2-}\\), \\(\\mathrm{Mn}^{2+}\\)",
      "\\(\\mathrm{MnO}_{4}^{2-}\\), \\(\\mathrm{Mn}^{2+}\\), \\(\\mathrm{MnO}_{2}\\)",
      "\\(\\mathrm{Mn}^{2+}\\), \\(\\mathrm{Mn}^{4+}\\), \\(\\mathrm{MnO}_{2}\\)"
    ],
    "correctOption": "1",
    "markscheme": "At \\(\\mathrm{pH}<7\\) it reduced to colourless substance which is \\(\\mathrm{Mn}^{2+}\\). At \\(\\mathrm{pH}=7\\), it form a brown color precipitate of \\(\\mathrm{MnO}_{2}\\). At \\(\\mathrm{pH}>7\\), it forms a green coloured compound name as \\(\\mathrm{MnO}_{4}{ }^{2-}\\).",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "8",
    "text": "Molecules are the constituent particles of molecular solids. Identify the molecular solid amongst the following;\n(1) \\(\\mathrm{SO}_{2}\\)\n(2) C\n(3) Fe\n(4) NaCl",
    "subject": "Chemistry",
    "topic": "Solid State",
    "subtopic": "Types of Solids",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["\\(\\mathrm{SO}_{2}\\)", "C", "Fe", "NaCl"],
    "correctOption": "1",
    "markscheme": "Molecular solids are the solids in which smaller number of atoms strongly bonded together i.e., \\(\\mathrm{CO}_{2}, \\mathrm{SO}_{2}, \\mathrm{H}_{2} \\mathrm{O}, Naphthalene, gasoline etc.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "9",
    "text": "Which of the following reaction will give t-Butyl ethyl ether by Williamson synthesis?\n\n(1)\n\n![](https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-02.jpg?height=165&width=532&top_left_y=2456&top_left_x=343)\n\n(2)\n\n![](https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-02.jpg?height=165&width=538&top_left_y=252&top_left_x=1177)\n\n(3)\n\n<smiles>CC([18OH])[CH][NH2+]C(C)C</smiles>\n\n(4)\n\n![](https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-02.jpg?height=115&width=626&top_left_y=574&top_left_x=1174)",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Williamson Synthesis",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-02.jpg?height=165&width=532&top_left_y=2456&top_left_x=343",
      "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-02.jpg?height=165&width=538&top_left_y=252&top_left_x=1177",
      "<smiles>CC([18OH])[CH][NH2+]C(C)C</smiles>",
      "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-02.jpg?height=115&width=626&top_left_y=574&top_left_x=1174"
    ],
    "correctOption": "1",
    "markscheme": "Williamson synthesis involve the reaction of alkoxide with alkyl halide to form ether. Here, the correct pair of reactant used for the preparation of t-butyl ethyl ether are sodium t-butoxide and ethyl chloride.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-02.jpg?height=165&width=532&top_left_y=2456&top_left_x=343"
  },
  {
    "exam": "CUET",
    "questionId": "10",
    "text": "Electrolysis of molten NaCl gives:\n\n(1) \\(\\mathrm{H}_{2}\\) at cathode, \\(\\mathrm{CI}_{2}\\) at anode and NaOH solution\n\n(2) Na at cathode, \\(\\mathrm{Cl}_{2}\\) at anode and NaOH solution\n\n(3) \\(\\mathrm{H}_{2}\\) at anode, \\(\\mathrm{Cl}_{2}\\) at cathode\n\n(4) Na at cathode and \\(\\mathrm{Cl}_{2}\\) at anode",
    "subject": "Chemistry",
    "topic": "Electrochemistry",
    "subtopic": "Electrolysis",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "\\(\\mathrm{H}_{2}\\) at cathode, \\(\\mathrm{CI}_{2}\\) at anode and NaOH solution",
      "Na at cathode, \\(\\mathrm{Cl}_{2}\\) at anode and NaOH solution",
      "\\(\\mathrm{H}_{2}\\) at anode, \\(\\mathrm{Cl}_{2}\\) at cathode",
      "Na at cathode and \\(\\mathrm{Cl}_{2}\\) at anode"
    ],
    "correctOption": "4",
    "markscheme": "Explanation: \\(\\mathrm{NaCl} \\rightarrow \\mathrm{Na}^{+}(l)+\\mathrm{Cl}^{-}(l)\\)\n\nAt cathode: reduction of \\(2 \\mathrm{Na}^{+}(\\mathrm{l})+2 \\mathrm{e}^{-} \\rightarrow 2 \\mathrm{Na}(\\mathrm{l})\\)\n\nAt anode: oxidation of \\(2 \\mathrm{CI}^{-}(\\mathrm{l}) \\rightarrow \\mathrm{Cl}_{2}(\\mathrm{~g})+2^{\\mathrm{e}-}\\)\n\nNet reaction is written as: \\(2 \\mathrm{Na}^{+}(\\mathrm{l})+2 \\mathrm{Cl}^{-}(\\mathrm{l}) \\rightarrow 2 \\mathrm{Na}(\\mathrm{l})+\\mathrm{Cl}_{2}(\\mathrm{~g})\\)",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "11",
    "text": "Which two transition metal ions has same 3d electronic configuration?\n(A) \\(\\mathrm{Mn}^{3+}\\)\n(B) \\(\\mathrm{Fe}^{2+}\\)\n(C) \\(\\mathrm{Mn}^{2+}\\)\n(D) \\(\\mathrm{Fe}^{3+}\\)\n(E) \\(\\mathrm{Cr}^{3+}\\)\n\nChoose the correct answer from the options given below:\n(1) (A) and (B) only\n(2) (B) and (C) only\n(3) (C) and (D) only\n(4) (D) and (E) only",
    "subject": "Chemistry",
    "topic": "Transition Elements",
    "subtopic": "Electronic Configuration",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["(A) and (B) only", "(B) and (C) only", "(C) and (D) only", "(D) and (E) only"],
    "correctOption": "3",
    "markscheme": "(A) The electronic configuration for a \\(\\mathrm{Mn}^{3+}\\) ion is \\([\\mathrm{Ar}] 3 \\mathrm{d}^{4}\\).\n(B) The electronic configuration for \\(\\mathrm{Fe}^{2+}\\) ion is \\([\\mathrm{Ar}] 3 \\mathrm{d}^{6}\\).\n(C) The electronic configuration for \\(\\mathrm{Mn}^{2+}\\) ion is \\([\\mathrm{Ar}] 3 \\mathrm{d}^{5}\\).\n(D) The electronic configuration for a \\(\\mathrm{Fe}^{3+}\\) ion is \\([\\mathrm{Ar}] 3 \\mathrm{d}^{5}\\).\n(E) The electronic configuration for a \\(\\mathrm{Cr}^{3+}\\) ion is \\([\\mathrm{Ar}] 3 \\mathrm{d}^{5} 4 \\mathrm{s}^{1}\\).",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "12",
    "text": "Limiting molar conductivity of \\(\\mathrm{H}_{2} \\mathrm{O}\\) is equal to:\n\n(1) \\(\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NaCl}+\\Lambda_{\\mathrm{m}^{\\circ}} \\mathrm{HCl}-\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NaOH}\\)\n\n(2) \\(\\Lambda^{\\circ} \\mathrm{m} \\mathrm{HC} 1+\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NaOH}-\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NaCl}\\)\n\n(3) \\(\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{HCl}+\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NH}_{4} \\mathrm{OH}-\\Lambda^{\\circ} \\mathrm{m} \\mathrm{NaCl}\\)\n\n(4) \\(\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NaCl}+\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{HCl}-\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NH}_{4} \\mathrm{OH}\\)",
    "subject": "Chemistry",
    "topic": "Electrochemistry",
    "subtopic": "Molar Conductivity",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "\\(\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NaCl}+\\Lambda_{\\mathrm{m}^{\\circ}} \\mathrm{HCl}-\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NaOH}\\)",
      "\\(\\Lambda^{\\circ} \\mathrm{m} \\mathrm{HC} 1+\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NaOH}-\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NaCl}\\)",
      "\\(\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{HCl}+\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NH}_{4} \\mathrm{OH}-\\Lambda^{\\circ} \\mathrm{m} \\mathrm{NaCl}\\)",
      "\\(\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NaCl}+\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{HCl}-\\Lambda_{\\mathrm{m}}^{\\circ} \\mathrm{NH}_{4} \\mathrm{OH}\\)"
    ],
    "correctOption": "2",
    "markscheme": "Explanation: \\(\\begin{aligned}\n& \\text { Explanation: } \\\\\n& \\qquad \\begin{array}{l}\n\\Lambda_{\\mathrm{m}} \\mathrm{HCl} \\longrightarrow \\Lambda_{\\mathrm{m}} \\mathrm{H}^{+}+\\Lambda_{\\mathrm{m}} \\mathrm{Cl}^{-} \\\\\n+\\Lambda_{\\mathrm{m}} \\mathrm{NaOH} \\longrightarrow \\Lambda_{\\mathrm{m}} \\mathrm{Na}^{+}+\\Lambda_{\\mathrm{m}} \\mathrm{OH}^{-} \\\\\n-\\Lambda_{\\mathrm{m}} \\mathrm{NaCl} \\longrightarrow \\Lambda_{\\mathrm{m}} \\mathrm{Na}^{+}+\\Lambda_{\\mathrm{m}} \\mathrm{Cl} \\\\\n\\\\\n\\Lambda_{\\mathrm{m}} \\mathrm{H}_{2} \\mathrm{O} \\longrightarrow \\Lambda_{\\mathrm{m}} \\mathrm{H}^{+}+\\Lambda_{\\mathrm{m}} \\mathrm{OH}^{-}\n\\end{array}\n\\end{aligned}\\)",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "13",
    "text": "A cell is prepared by dipping a Cu rod in \\(1 \\mathrm{M} \\mathrm{CuSO}_{4}\\) solution and Sn rod in \\(1 \\mathrm{M} \\mathrm{SnCl}_{2}\\) solution. The standard electrode potential of Cu is +0.34 V and Sn is -0.14 V . Emf of cell will be:\n(1) 0.48 V\n(2) 0.20 V\n(3) 0.34 V\n(4) 0.14 V",
    "subject": "Chemistry",
    "topic": "Electrochemistry",
    "subtopic": "Electrochemical Cells",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["0.48 V", "0.20 V", "0.34 V", "0.14 V"],
    "correctOption": "1",
    "markscheme": "Explanation: \\(\\begin{aligned}\n\\mathrm{E}^{\\mathrm{o}} & =\\mathrm{E}_{\\mathrm{c}}-\\mathrm{E}_{\\mathrm{a}} \\\\\n& =0.34-(-0.14) \\\\\n& =0.48 \\mathrm{~V}\n\\end{aligned}\\)",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "14",
    "text": "On passing ammonia gas through a solution of copper sulphate, a deep blue solution is obtained. The deep blue colour of the solution is due to the formation of:\n(1) \\(\\left[\\mathrm{Cu}\\left(\\mathrm{NH}_{3}\\right)_{2}\\right]^{2+}\\)\n(2) \\(\\left[\\mathrm{Cu}\\left(\\mathrm{NH}_{3}\\right)_{4}\\right]^{2+}\\)\n(3) \\(\\left[\\mathrm{Cu}\\left(\\mathrm{NH}_{3}\\right)_{6}\\right]^{+}\\)\n(4) \\(\\left[\\mathrm{Cu}\\left(\\mathrm{NH}_{3}\\right)_{6}\\right]^{2+}\\)",
    "subject": "Chemistry",
    "topic": "Coordination Chemistry",
    "subtopic": "Formation of Complex Ions",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "\\(\\left[\\mathrm{Cu}\\left(\\mathrm{NH}_{3}\\right)_{2}\\right]^{2+}\\)",
      "\\(\\left[\\mathrm{Cu}\\left(\\mathrm{NH}_{3}\\right)_{4}\\right]^{2+}\\)",
      "\\(\\left[\\mathrm{Cu}\\left(\\mathrm{NH}_{3}\\right)_{6}\\right]^{+}\\)",
      "\\(\\left[\\mathrm{Cu}\\left(\\mathrm{NH}_{3}\\right)_{6}\\right]^{2+}\\)"
    ],
    "correctOption": "2",
    "markscheme": "Explanation: Deep blue colour developed by addition of excess of ammonia gas in copper Sulphate solution and the formed complex is \\(\\left[\\mathrm{Cu}\\left(\\mathrm{NH}_{3}\\right)_{4}\\right]^{2+}\\).",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "15",
    "text": "The correct increasing basicity in aqueous medium for (I) \\(\\mathrm{NH}_{3}\\) (II) \\(\\mathrm{CH}_{3} \\mathrm{CH}_{2} \\mathrm{CH}_{2}\\) (III) \\(\\left(\\mathrm{CH}_{3} \\mathrm{CH}_{2}\\right)_{2} \\mathrm{NH}\\) (IV) \\(\\left(\\mathrm{CH}_{3} \\mathrm{CH}_{2}\\right)_{3} \\mathrm{~N}\\) is:\n(A) (II) $<$ (I) $<$ (IV) $<$ (III)\n(B) (II) $<$ (I) $<$ (III) $<$ (IV)\n(C) (I) $<$ (II) $<$ (IV) $<$ (III)\n(D) (I) $>$ (II) $>$ (IV) $>$ (III)\n\nChoose the correct answer from the options given below:\n(1) (C)\n(2) (B)\n(3) (D)\n(4) (A)",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Basicity of Amines",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(C)",
      "(B)",
      "(D)",
      "(A)"
    ],
    "correctOption": "3",
    "markscheme": "Explanation: The basicity of amine and alkyl amine depends upon the +I effect and Steric effect.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "16",
    "text": "<smiles>Oc1cccc(Cl)c1O</smiles>\n\nProduct 'A' is:\n(1) Salicylaldehyde\n(2) Benzoic acid\n(3) p -Chloro benzoic acid\n(4) Salicylic acid",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Identification of Organic Compounds",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Salicylaldehyde", "Benzoic acid", "p-Chloro benzoic acid", "Salicylic acid"],
    "correctOption": "4",
    "markscheme": "",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-03.jpg?height=653&width=725&top_left_y=1992&top_left_x=288"
  },
  {
    "exam": "CUET",
    "questionId": "17",
    "text": "Match List-I with List-II.\n\n\\begin{tabular}{|ll|ll|}\n\\hline \\multicolumn{2}{|c|}{ List - I } & \\multicolumn{2}{|c|}{ List - II } \\\\\n\\hline (A) & {\\(\\left[\\mathrm{Ni}(\\mathrm{CN})_{4}{ }^{2-}\\right.\\} & (I) & EDTA \\\\\n(B) & bidentate & (II) & paramagnetic \\\\\n(C) & chelate ligand & (III) & diamagnetic \\\\\n(D) & {\\(\\left[\\mathrm{NiCl}_{4}\\right]^{2-}\\} & (IV) & oxalate \\\\\n\\hline\n\\end{tabular}\n\nChoose the correct answer from the options given below\n\n(1) (A)-(III), (B)-(IV), (C)-(l), (D)-(II)\n\n(2) (A)-(II), (B)-(IV), (C)-(I), (D)-(III)\n\n(3) (A)-(III), (B)-(I), (C)-(IV), (D)-(II)\n\n(4) (A)-(II), (B)-(I), (C)-(IV), (D)-(III)",
    "subject": "Chemistry",
    "topic": "Coordination Chemistry",
    "subtopic": "Ligands and Complexes",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A)-(III), (B)-(IV), (C)-(l), (D)-(II)",
      "(A)-(II), (B)-(IV), (C)-(I), (D)-(III)",
      "(A)-(III), (B)-(I), (C)-(IV), (D)-(II)",
      "(A)-(II), (B)-(I), (C)-(IV), (D)-(III)"
    ],
    "correctOption": "1",
    "markscheme": "(A) In \\(\\left[\\mathrm{Ni}(\\mathrm{CN})_{4}\\right]^{2-}, \\mathrm{CN}^{-}\\)is a strong field ligand which allows the pairing of the electrons and diamagnetic in nature.\n(B) Oxalate is an example of bidentate ligand.\n(C) EDTA is a chelating agent.\n(D) \\operatorname{In}\\left[\\mathrm{Ni}(\\mathrm{Cl})_{4}\\right]^{2}, \\mathrm{Cl}^{-}\\)is a weak field ligand which do not allow the pairing of the electrons in an orbital. Hence, it is paramagnetic in nature.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "18",
    "text": "Identify the biodegradable polymer in the following:\n(1) Nylon -6,6\n(2) PVC\n(3) Polythene\n(4) PHBV",
    "subject": "Chemistry",
    "topic": "Polymers",
    "subtopic": "Biodegradable Polymers",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Nylon -6,6", "PVC", "Polythene", "PHBV"],
    "correctOption": "4",
    "markscheme": "PHBV is poly -3-hydroxy butyrate Co-3-hydroxy valerate. It is biodegradable, nontoxic and bio-compatible plastic polymer.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "19",
    "text": "Which of the following statements are correct about alkyl halides:\n\n(A) Alkylhalides are polar so they are soluble in water\n\n(B) RX on reaction with alc. KOH give alkenes\n\n(C) RX on reaction with \\(\\mathrm{AgNO}_{2}\\) give RONO\n\n(D) \\(\\mathrm{S}_{\\mathrm{N}}\\) proceeds with inversion in configuration\n\n(E) R - X have higher boiling point than parent alkanes\n\nChoose the correct answer from the options given below:\n(1) (B), (E) only\n(2) (A), (C) only\n(3) (D), (E) only\n(4) (B), (C) only",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Reactions of Alkyl Halides",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["(B), (E) only", "(A), (C) only", "(D), (E) only", "(B), (C) only"],
    "correctOption": "1",
    "markscheme": "Explanation: Explanation: Many properties of metal like lustre, electrical and thermal conductivity depends upon free electrons.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-03.jpg?height=360&width=714&top_left_y=1988&top_left_x=1133"
  },
  {
    "exam": "CUET",
    "questionId": "20",
    "text": "When 1.5 g of a non-volatile solute is dissolved in 30 g of a solvent, the boiling point of the solvent is raised by 2 K . Calculate the molar mass of the solute, given that \\(\\mathrm{K}_{\\mathrm{b}}\\) for the solvent is \\(1.85 \\mathrm{~K} \\mathrm{~kg} \\mathrm{~mol}^{-1}\\).\n(1) \\(46.25 \\mathrm{~g} \\mathrm{~mol}^{-1}\\)\n(2) \\(103 \\mathrm{~g} \\mathrm{~mol}^{-1}\\)\n(3) \\(94 \\mathrm{~g} \\mathrm{~mol}^{-1}\\)\n(4) \\(23 \\mathrm{~g} \\mathrm{~mol}^{-1}\\)",
    "subject": "Chemistry",
    "topic": "Solutions",
    "subtopic": "Boiling Point Elevation",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["46.25 g/mol", "103 g/mol", "94 g/mol", "23 g/mol"],
    "correctOption": "1",
    "markscheme": "Explanation: \\(\\begin{aligned}\n& \\text { Explanation: } \\\\\n& \\qquad \\begin{aligned}\n\\mathrm{M}_{\\mathrm{B}} & =\\frac{\\mathrm{K}_{\\mathrm{b}} \\times \\mathrm{W}_{\\mathrm{B}} \\times 1000}{\\Delta \\mathrm{T}_{\\mathrm{b}} \\times \\mathrm{W}_{\\mathrm{A}}} \\\\\n& =\\frac{1.85 \\times 1.5 \\times 1000}{2 \\times 30} \\\\\n& =46.25 \\mathrm{~g} \\mathrm{~mol}^{-1}\n\\end{aligned}\n\\end{aligned}\\)",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "21",
    "text": "Which of the following statements are true?\n\n(A) Noble gases have low M.P. or B.P. due to weak dispersion forces.\n\n(B) All noble gases have completely filled \\(n s^{2} n p^{6}\\) electronic configuration.\n\n(C) \\(\\mathrm{XeF}_{2}\\) and \\(\\mathrm{XeF}_{6}\\) are colourless crystalline solid.\n\n(D) \\(\\mathrm{XeO}_{3}\\) has pyramidal geometry.\n\nChoose the correct answer from the options given below:\n\n(1) (A), (C) only\n\n(2) (B), (C), (D) only\n\n(3) (A), (B), (C), (D) only\n\n(4) (A), (C), (D) only",
    "subject": "Chemistry",
    "topic": "Periodic Table",
    "subtopic": "Properties of Noble Gases",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A), (C) only",
      "(B), (C), (D) only",
      "(A), (B), (C), (D) only",
      "(A), (C), (D) only"
    ],
    "correctOption": "4",
    "markscheme": "Explanation: All noble gases have low melting and boiling point due to weak dispersion forces of attraction. \\(\\mathrm{XeF}_{2}\\) and \\(\\mathrm{XeF}_{4}\\) are colourless crystalline solids. \\(\\mathrm{XeO}_{3}\\) has pyramidal symmetry",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-04.jpg?height=277&width=444&top_left_y=1343&top_left_x=324"
  },
  {
    "exam": "CUET",
    "questionId": "22",
    "text": "The entities which do not dissociate into simple ions are:\n(A) \\(\\left[\\mathrm{Fe}(\\mathrm{CN})_{6}\\right]^{4}\\)\n(B) \\(\\mathrm{KCl} \\cdot \\mathrm{MgCl}_{2} \\cdot 6 \\mathrm{H}_{2} \\mathrm{O}\\)\n(C) \\(\\mathrm{K}_{4}\\left[\\mathrm{Fe}(\\mathrm{CN})_{6}\\right]\\)\n(D) \\(\\mathrm{KAl}\\left(\\mathrm{SO}_{4}\\right)_{2} \\cdot 12 \\mathrm{H}_{2} \\mathrm{O}\\)\n(E) \\(\\mathrm{FeSO}_{4} \\cdot\\left(\\mathrm{NH}_{4}\\right) 2 \\mathrm{SO}_{4} \\cdot 6 \\mathrm{H}_{2} \\mathrm{O}\\)\n\nChoose the correct answer from the options given below:\n(1) (A) and (C) only\n(2) (B) and (D) only\n(3) (D) and (E) only\n(4) (A) and (B) only",
    "subject": "Chemistry",
    "topic": "Coordination Chemistry",
    "subtopic": "Complex Ions",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A) and (C) only",
      "(B) and (D) only",
      "(D) and (E) only",
      "(A) and (B) only"
    ],
    "correctOption": "1",
    "markscheme": "Explanation: Both are the complex coordination compounds and remains unchanged. They do not have water of crystallization in their structures.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "23",
    "text": "Ethanol cannot be prepared from:\n\n(1)\n\n<smiles>CCOC(=O)c1ccccc1</smiles>\n\n(2) \\(\\mathrm{CH}_{3} \\mathrm{CH}_{2} \\mathrm{CH}_{2} \\mathrm{COOC}_{2} \\mathrm{H}_{5}\\)\n\n(3) \\(\\mathrm{C}_{2} \\mathrm{H}_{5} \\mathrm{COOCH}_{3}\\)\n\n(4) \\(\\mathrm{CH}_{3} \\mathrm{COOC}_{2} \\mathrm{H}_{5}\\)",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Preparation of Alcohols",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "<smiles>CCOC(=O)c1ccccc1</smiles>",
      "\\(\\mathrm{CH}_{3} \\mathrm{CH}_{2} \\mathrm{CH}_{2} \\mathrm{COOC}_{2} \\mathrm{H}_{5}\\)",
      "\\(\\mathrm{C}_{2} \\mathrm{H}_{5} \\mathrm{COOCH}_{3}\\)",
      "\\(\\mathrm{CH}_{3} \\mathrm{COOC}_{2} \\mathrm{H}_{5}\\)"
    ],
    "correctOption": "3",
    "markscheme": "Explanation: Methyl propanoate on reduction gives Propanol and Methanol.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-04.jpg?height=140&width=758&top_left_y=364&top_left_x=1070"
  },
  {
    "exam": "CUET",
    "questionId": "24",
    "text": "Arrange the following in the increasing order of their van't Hoff factors\n\n(A) Very dilute \\(\\mathrm{MgCl}_{2}\\) solution\n\n(B) Very dilute \\(\\mathrm{AlCl}_{3}\\) solution\n\n(C) Very dilute NaCl solution\n\n(D) Very dilute \\(\\mathrm{Al}_{2} \\mathrm{O}_{3}\\) solution\n\n(E) Very dilute urea solution\n\nChoose the correct answer from the options given below:\n\n(1) (E) $<$ (C) $<$ (A) $<$ (B) $<$ (D)\n\n(2) (E) $<$ (C) $<$ (A) $<$ (D) $<$ (B)\n\n(3) (E) $<$ (C) $<$ (B) $<$ (A) $<$ (D)\n\n(4) (E) $<$ (B) $<$ (A) $<$ (D) $<$ (C)",
    "subject": "Chemistry",
    "topic": "Solutions",
    "subtopic": "van't Hoff Factor",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(E) < (C) < (A) < (B) < (D)",
      "(E) < (C) < (A) < (D) < (B)",
      "(E) < (C) < (B) < (A) < (D)",
      "(E) < (B) < (A) < (D) < (C)"
    ],
    "correctOption": "3",
    "markscheme": "Explanation: van't Hoff factor (i) is the ratio of actual number of particles in solution after dissociation or association to the number of formula units initially dissolved in solution. For different compounds in dilute solutions, the van't Hoff factors are as follows:\n(A) \\(\\mathrm{MgCl}_{2}\\) solution: 3\n(B) \\(\\mathrm{AlCl}_{3}\\) solution: 4\n(C) NaCl solution: 2\n(D) \\(\\mathrm{Al}_{2} \\mathrm{O}_{3}\\) solution: 5\n(E) urea solution: 1\n\nThus, the increasing order of their van't Hoff factors is: \\(E < C < A < B < D\\).",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "25",
    "text": "Match List - I with List - II.\n\nChoose the correct answer from the options given below:\n\n(1) (A)-(I), (B)-(II), (C)-(III), (D)-(IV)\n\n(2) (A)-(III), (B)-(I), (C)-(IV), (D)-(II)\n\n(3) (A)-(III), (B)-(II), (C)-(IV), (D)-(I)\n\n(4) (A)-(I), (B)-(IV), (C)-(II), (D)-(III)",
    "subject": "Chemistry",
    "topic": "Biochemistry",
    "subtopic": "Proteins",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A)-(I), (B)-(II), (C)-(III), (D)-(IV)",
      "(A)-(III), (B)-(I), (C)-(IV), (D)-(II)",
      "(A)-(III), (B)-(II), (C)-(IV), (D)-(I)",
      "(A)-(I), (B)-(IV), (C)-(II), (D)-(III)"
    ],
    "correctOption": "2",
    "markscheme": "Explanation: Denaturation is a process in which proteins denature at high temperature, loose its identity and remains in primary structure Primary structure is a sequence of amino acid Secondary structure consist of \\(\\alpha\\)-helix and \\(\\beta\\)-pleated sheets. Quaternary struture is the spatial arrangement of sub-units with respect to each other (consist of two or more polypeptide chain).",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-04.jpg?height=244&width=431&top_left_y=1146&top_left_x=1135"
  },
  {
    "exam": "CUET",
    "questionId": "26",
    "text": "Match List - 1 with List - II.\n\nList -I\n\n(A)\n\n<smiles>NC1CCCCC1Br</smiles>\n\nList -II\n\n(I)\n\n(B)\n\n<smiles>Cl[Mg]C1CCCCC1</smiles>\n\n![](https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-05.jpg?height=93&width=206&top_left_y=505&top_left_x=473)\n\n<smiles>Nc1c(Br)cc(Br)cc1Br</smiles>\n\n(C)\n\n<smiles>Cl[Mg]c1ccccc1</smiles>\n\\(\\xrightarrow[\\text { (2) } \\mathrm{NaNO}_{2}, \\Delta]{\\text { (1) } \\mathrm{HBF}_{4}}\\) (II)\n\n<smiles>Nc1ccc([N+](=O)[O-])cc1</smiles>\n\n(D)\n\n<smiles>Nc1ccccc1</smiles>\n\n<smiles>O=[N+](O)[Al-][C+]([Al])C=CC1CCCCC1</smiles>\n\nChoose the correct answer from the options given below:\n\n(1) (A)-(II), (B)-(IV), (C)-(III), (D)-(I)\n\n(2) (A)-(III), (B)-(II), (Q-(IV), (D)-(I)\n\n(3) (A)-(II), (B)-(III), (C)-(IV), (D)-(I)\n\n(4) (A), (I), (B)-(II), (C)-(III), (D)-(IV)",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Reactions and Products",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A)-(II), (B)-(IV), (C)-(III), (D)-(I)",
      "(A)-(III), (B)-(II), (Q-(IV), (D)-(I)",
      "(A)-(II), (B)-(III), (C)-(IV), (D)-(I)",
      "(A), (I), (B)-(II), (C)-(III), (D)-(IV)"
    ],
    "correctOption": "3",
    "markscheme": "",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "27",
    "text": "Manganese ions on reaction with peroxydisulphate ions form:\n(1) \\(\\mathrm{MnO}_{4}^{2-}\\)\n(2) \\(\\mathrm{MnO}_{2}\\)\n(3) \\(\\mathrm{Mn}_{2} \\mathrm{O}_{7}\\)\n(4) \\(\\mathrm{MnO}_{4}^{-}\\)",
    "subject": "Chemistry",
    "topic": "Redox Reactions",
    "subtopic": "Oxidation States",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "\\(\\mathrm{MnO}_{4}^{2-}\\)",
      "\\(\\mathrm{MnO}_{2}\\)",
      "\\(\\mathrm{Mn}_{2} \\mathrm{O}_{7}\\)",
      "\\(\\mathrm{MnO}_{4}^{-}\\)"
    ],
    "correctOption": "4",
    "markscheme": "Explanation: \\(2 \\mathrm{Mn}^{2+}+5 \\mathrm{~S}_{2} \\mathrm{O}_{8}{ }^{2-}+8 \\mathrm{H}_{2} \\mathrm{O} \\rightarrow 2 \\mathrm{MnO}_{4}^{-}+10 \\mathrm{SO}_{4}{ }^{2-}+16 \\mathrm{H}^{+}\\)",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "28",
    "text": "Glycosidic linkage is formed by:\n\n(1) Elimination of water molecule\n\n(2) Addition of water molecule\n\n(3) Elimination of ammonia molecule\n\n(4) Addition of ammonia molecule",
    "subject": "Chemistry",
    "topic": "Biochemistry",
    "subtopic": "Carbohydrates",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "Elimination of water molecule",
      "Addition of water molecule",
      "Elimination of ammonia molecule",
      "Addition of ammonia molecule"
    ],
    "correctOption": "1",
    "markscheme": "Explanation: Glycosidic linkage formed by two monosaccharide units connected by a oxygen atom with the loss of one water molecule.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-05.jpg?height=409&width=645&top_left_y=1914&top_left_x=325"
  },
  {
    "exam": "CUET",
    "questionId": "29",
    "text": "\\(\\mathrm{t}_{99 \\%}\\) with respect to \\(\\mathrm{t}_{90 \\%}\\) for a first order reaction is\n\n(1) four times of \\(\\mathrm{t}_{50 \\%}\\)\n\n(2) one and half time\n\n(3) It is same\n\n(4) Double",
    "subject": "Chemistry",
    "topic": "Chemical Kinetics",
    "subtopic": "First Order Reactions",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "four times of \\(\\mathrm{t}_{50 \\%}\\)",
      "one and half time",
      "It is same",
      "Double"
    ],
    "correctOption": "4",
    "markscheme": "Explanation: \\(\\begin{aligned}\n\\text { for } \\begin{align*}\n\\mathrm{t}_{90 \\%}, \\text { at } & =\\frac{10 \\mathrm{a}_{\\mathrm{o}}}{100}=\\frac{\\mathrm{a}_{\\mathrm{o}}}{10} \\\\\n\\mathrm{t}_{90 \\%} & =\\frac{1}{\\mathrm{~K}} \\ell \\mathrm{n} \\frac{\\mathrm{a}_{\\mathrm{o}}}{\\mathrm{a}_{\\mathrm{o}} / 100}=\\frac{\\ln 10}{\\mathrm{~K}} \\tag{1}\n\\end{align*}\\)\n\nFor \\(\\_{99 \\%}, a_{t}=\\frac{1}{100} a_{o}\\)\n\n\\(\\begin{align*}\n\\mathrm{t}_{99 \\%} & =\\frac{1}{\\mathrm{~K}} \\ln \\frac{\\mathrm{a}_{\\mathrm{o}}}{\\mathrm{a}_{\\mathrm{o}} / 100} \\\\\n& =\\frac{2 \\ell \\mathrm{n} 10}{\\mathrm{~K}} \\tag{2}\n\\end{align*}\\)\n\nFrom equation (1) and (2)\n\n\\(\\begin{aligned}\n\\mathrm{t}_{99 \\%} & =2 \\times \\mathrm{t}_{90 \\%} \\\\\n\\mathrm{x} & =2\n\\end{aligned}\\)",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "29",
    "text": "\\(\\mathrm{t}_{99 \\%}\\) with respect to \\(\\mathrm{t}_{90 \\%}\\) for a first order reaction is\n\n(1) four times of \\(\\mathrm{t}_{50 \\%}\\)\n\n(2) one and half time\n\n(3) It is same\n\n(4) Double",
    "subject": "Chemistry",
    "topic": "Chemical Kinetics",
    "subtopic": "First Order Reactions",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "four times of \\(\\mathrm{t}_{50 \\%}\\)",
      "one and half time",
      "It is same",
      "Double"
    ],
    "correctOption": "4",
    "markscheme": "Explanation: \\(\\begin{aligned}\n\\text { for } \\begin{align*}\n\\mathrm{t}_{90 \\%}, \\text { at } & =\\frac{10 \\mathrm{a}_{\\mathrm{o}}}{100}=\\frac{\\mathrm{a}_{\\mathrm{o}}}{10} \\\\\n\\mathrm{t}_{90 \\%} & =\\frac{1}{\\mathrm{~K}} \\ell \\mathrm{n} \\frac{\\mathrm{a}_{\\mathrm{o}}}{\\mathrm{a}_{\\mathrm{o}} / 100}=\\frac{\\ln 10}{\\mathrm{~K}} \\tag{1}\n\\end{align*}\\)\n\nFor \\(\\_{99 \\%}, a_{t}=\\frac{1}{100} a_{o}\\)\n\n\\(\\begin{align*}\n\\mathrm{t}_{99 \\%} & =\\frac{1}{\\mathrm{~K}} \\ln \\frac{\\mathrm{a}_{\\mathrm{o}}}{\\mathrm{a}_{\\mathrm{o}} / 100} \\\\\n& =\\frac{2 \\ell \\mathrm{n} 10}{\\mathrm{~K}} \\tag{2}\n\\end{align*}\\)\n\nFrom equation (1) and (2)\n\n\\(\\begin{aligned}\n\\mathrm{t}_{99 \\%} & =2 \\times \\mathrm{t}_{90 \\%} \\\\\n\\mathrm{x} & =2\n\\end{aligned}\\)",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "30",
    "text": "Match List -1 with List - II.\n\n\\begin{tabular}{|l|l|}\n\\hline \\multicolumn{1}{|c|}{ List -I } & \\multicolumn{1}{|c|}{ List - II } \\\\\n\\hline (A) Molarity & (I) \\begin{tabular}{l} \nNumber of moles \\\\\nof solute/kilogram \\\\\nof solvent\n\\end{tabular} \\\\\n(B) Molality & \\begin{tabular}{l} \n(II) \\begin{tabular}{l} \nOsmotic pressure \\\\\n(III)\n\\end{tabular} \\\\\nNumber of moles \\\\\nof solute/litre of \\\\\nsolution\n\\end{tabular} \\\\\n(D) Non-ideal solution & (IV) \\begin{tabular}{l} \nDeviation from \\\\\nRaoult's Law\n\\end{tabular} \\\\\n\\hline\n\\end{tabular}\n\nChoose the correct answer from the options given below:\n\n(1) (A)-(III), (B)-(I), (C)-(II), (D)-(IV)\n\n(2) (A)-(III), (B)-(I), (C)-(II), (D)-(IV)\n\n(3) (A)-(I), (B)-(III), (C)-(II), (D)-(IV)\n\n(4) (A)-(I), (B)-(III), (C)-(IV), (D)-(II)",
    "subject": "Chemistry",
    "topic": "Solutions",
    "subtopic": "Concentration Terms",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A)-(III), (B)-(I), (C)-(II), (D)-(IV)",
      "(A)-(III), (B)-(I), (C)-(II), (D)-(IV)",
      "(A)-(I), (B)-(III), (C)-(II), (D)-(IV)",
      "(A)-(I), (B)-(III), (C)-(IV), (D)-(II)"
    ],
    "correctOption": "2",
    "markscheme": "Explanation: Molarity is number of moles of solute dissolve per litre of solution. Molality is number of moles of solutes dissolve per kilogram of solvent. Osmosis is one of the colligative property. Non-ideal solutions do not follows Raoult's Law.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "31",
    "text": "The decomposition of ammonia on platinum surface is a zero order reaction. How much time it will take for $1 \\times 10^{-4} \\mathrm{~mol} \\mathrm{~L}^{-1}$ of ammonia to reduce into half of its concentration?\n\n\\left(\\mathrm{K}=0.5 \\times 10^{-4} \\mathrm{~mol} \\mathrm{~L}^{-1} \\mathrm{~s}^{-1}\\right)\n(1) 1 s\n(2) 10 s\n(3) 100 s\n(4) 5 s",
    "subject": "Chemistry",
    "topic": "Chemical Kinetics",
    "subtopic": "Zero Order Reactions",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "1 s",
      "10 s",
      "100 s",
      "5 s"
    ],
    "correctOption": "1",
    "markscheme": "Explanation: \\(\\begin{aligned}\n\\left(\\mathrm{A}_{0}\\right) & =1 \\times 10^{-4} \\\\\n(\\mathrm{~A}) & =\\frac{1 \\times 10^{-4}}{2}=0.5 \\times 10^{-4} \\\\\n\\mathrm{t} & =\\frac{\\mathrm{A}_{0}-\\mathrm{A}}{\\mathrm{K}} \\\\\n\\mathrm{t} & =\\frac{1 \\times 10^{-4}-0.5 \\times 10^{-4}}{0.5 \\times 10^{-4}} \\\\\n\\mathrm{t} & =1 \\mathrm{~s}\n\\end{aligned}\\)",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "32",
    "text": "Identify the correct statement:\n\n(1) \\(\\mathrm{CrO}\\) is acidic, \\(\\mathrm{Cr}_{2} \\mathrm{C}_{3}\\) is basic, \\(\\mathrm{CrO}_{3}\\) is amphoteric.\n\n(2) \\(\\mathrm{CrO}\\) is basic, \\(\\mathrm{Cr}_{2} \\mathrm{C}_{3}\\) is acidic, \\(\\mathrm{CrO}_{3}\\) is amphoteric.\n\n(3) \\(\\mathrm{CrO}\\) is basic, \\(\\mathrm{Cr}_{2} \\mathrm{C}_{3}\\) is amphoteric, \\(\\mathrm{CrO}_{3}\\) is acidic.\n\n(4) \\(\\mathrm{CrO}\\) is amphoteric, \\(\\mathrm{Cr}_{2} \\mathrm{C}_{3}\\) is basic, \\(\\mathrm{CrO}_{3}\\) is acidic.",
    "subject": "Chemistry",
    "topic": "Periodic Table",
    "subtopic": "Oxides of Elements",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "\\(\\mathrm{CrO}\\) is acidic, \\(\\mathrm{Cr}_{2} \\mathrm{C}_{3}\\) is basic, \\(\\mathrm{CrO}_{3}\\) is amphoteric.",
      "\\(\\mathrm{CrO}\\) is basic, \\(\\mathrm{Cr}_{2} \\mathrm{C}_{3}\\) is acidic, \\(\\mathrm{CrO}_{3}\\) is amphoteric.",
      "\\(\\mathrm{CrO}\\) is basic, \\(\\mathrm{Cr}_{2} \\mathrm{C}_{3}\\) is amphoteric, \\(\\mathrm{CrO}_{3}\\) is acidic.",
      "\\(\\mathrm{CrO}\\) is amphoteric, \\(\\mathrm{Cr}_{2} \\mathrm{C}_{3}\\) is basic, \\(\\mathrm{CrO}_{3}\\) is acidic."
    ],
    "correctOption": "3",
    "markscheme": "Explanation: Oxidation state of CrO is +2 , Oxidation state of \\(\\mathrm{Cr}_{2} \\mathrm{O}_{3}\\) is +3 and oxidation state of \\(\\mathrm{CrO}_{3}\\) is +6 . Lower oxidation states forms basic oxide, higher oxidation state forms amphoteric and acidic oxides.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "33",
    "text": "Which of the following is not a property of \\(\\alpha\\)-sulphur?\n\n(1) It is readily soluble in \\(\\mathrm{CS}_{2}\\)\n\n(2) It has monoclinic structure\n\n(3) This allotrope is yellow in colour.\n\n(4) It's melting point is 385.8 K .",
    "subject": "Chemistry",
    "topic": "Periodic Table",
    "subtopic": "Allotropes",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "It is readily soluble in \\(\\mathrm{CS}_{2}\\)",
      "It has monoclinic structure",
      "This allotrope is yellow in colour.",
      "It's melting point is 385.8 K ."
    ],
    "correctOption": "2",
    "markscheme": "Explanation: \\(\\alpha\\)-sulphur is known as rhombic sulphur while \\(\\beta\\)-sulphur is known as monoclinic sulphur.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "34",
    "text": "The following pentose sugar is obtained by complete hydrolysis of DNA, along with phosphoric acid and nitrogenous base:\n\n(1)\n\n<smiles>OC[C@H]1O[C@H](O)[C@H](O)[C@H]1O</smiles>\n\n(2)\n\n<smiles>OC[C@H]1O[C@H](O)[C@H](O)[C@H]1O</smiles>\n\n(3)\n\n<smiles>OC[C@H]1O[C@H](O)[C@H](O)[C@H]1O</smiles>\n\n(4)\n\n<smiles>CO[C@H]1O[C@H](O)[C@H]1O</smiles>",
    "subject": "Chemistry",
    "topic": "Biochemistry",
    "subtopic": "Nucleic Acids",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "<smiles>OC[C@H]1O[C@H](O)[C@H](O)[C@H]1O</smiles>",
      "<smiles>OC[C@H]1O[C@H](O)[C@H](O)[C@H]1O</smiles>",
      "<smiles>OC[C@H]1O[C@H](O)[C@H](O)[C@H]1O</smiles>",
      "<smiles>CO[C@H]1O[C@H](O)[C@H]1O</smiles>"
    ],
    "correctOption": "2",
    "markscheme": "Explanation: Complete hydrolysis of DNA give inorganic phosphate, 2-deoxyribose and one of four different heterocyclic bases.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "35",
    "text": "Lustre, electrical and thermal conductivity of metals can be explained by the theory of:\n\n(1) dipole-dipole interactions\n\n(2) Coulombic (electrostatic) forces\n\n(3) Sea of free electrons\n\n(4) London forces",
    "subject": "Chemistry",
    "topic": "Chemical Bonding",
    "subtopic": "Metallic Bond",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "dipole-dipole interactions",
      "Coulombic (electrostatic) forces",
      "Sea of free electrons",
      "London forces"
    ],
    "correctOption": "3",
    "markscheme": "Explanation: Many properties of metal like lustre, electrical and thermal conductivity depends upon free electrons.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "36",
    "text": "The integrated rate equation for a first order reaction \\(\\frac{k t}{2.303}\\) is \\(\\log R_{0}-\\log R_{t}\\). The straight line graph is obtained by plotting:\n\n(1) time vs \\(R_{t}\\)\n\n(2) time vs \\(\\log R_{t}\\)\n\n(3) time vs \\(\\frac{1}{R_{t}}\\)\n\n(4) time vs \\(R_{0}\\)",
    "subject": "Chemistry",
    "topic": "Chemical Kinetics",
    "subtopic": "First Order Reactions",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "time vs \\(R_{t}\\)",
      "time vs \\(\\log R_{t}\\)",
      "time vs \\(\\frac{1}{R_{t}}\\)",
      "time vs \\(R_{0}\\)"
    ],
    "correctOption": "2",
    "markscheme": "",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-06.jpg?height=494&width=711&top_left_y=870&top_left_x=1132"
  },
  {
    "exam": "CUET",
    "questionId": "37",
    "text": "The correct order of reactivity of following halides towards \\(\\mathrm{S}_{\\mathrm{N}} 1\\) reaction is:\n\n<smiles>Clc1ccccc1</smiles>\n(I)\n\n<smiles>ClCc1ccccc1</smiles>\n(II)\n\n<smiles>BrCc1ccccc1Br</smiles>\n(III)\n\n<smiles>CCc1ccccc1</smiles>\n(IV)\n\n(1) (IV) $>$ (III) $>$ (II) $>$ (I)\n\n(2) (I) $>$ (II) $>$ (III) $>$ (IV)\n\n(3) (IV) $>$ (II) $>$ (III) $>$ (I)\n\n(4) (I) $>$ (III) $>$ (II) $>$ (IV)",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Reactions and Mechanisms",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(IV) > (III) > (II) > (I)",
      "(I) > (II) > (III) > (IV)",
      "(IV) > (II) > (III) > (I)",
      "(I) > (III) > (II) > (IV)"
    ],
    "correctOption": "1",
    "markscheme": "Explanation: In \\(\\mathrm{S}_{\\mathrm{N}} 1\\) mechanism, reactivity decreases by intermediate benzyl carbocation formed in the slowest steps which is stabilized by resonance.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "38",
    "text": "The reaction of 3-methylbutan-2-ol with HBr , will give:\n\n(1) 2-Bromo-2-methylbutane\n\n(2) 3-Bromo-2-methylbutane\n\n(3) 3-Bromo-3-methylbutane\n\n(4) 2-Bromo-3-methylbutane",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Alcohols, Phenols and Ethers",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "2-Bromo-2-methylbutane",
      "3-Bromo-2-methylbutane",
      "3-Bromo-3-methylbutane",
      "2-Bromo-3-methylbutane"
    ],
    "correctOption": "1",
    "markscheme": "",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-06.jpg?height=211&width=793&top_left_y=2282&top_left_x=1047"
  },
  {
    "exam": "CUET",
    "questionId": "39",
    "text": "The shape of \\(\\mathrm{XeF}_{6}\\) is:\n(1) Regular octachedral\n(2) Square planar\n(3) Distorted octahedral\n(4) Square pyramidal",
    "subject": "Chemistry",
    "topic": "Chemical Bonding",
    "subtopic": "Molecular Geometry",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "Regular octachedral",
      "Square planar",
      "Distorted octahedral",
      "Square pyramidal"
    ],
    "correctOption": "3",
    "markscheme": "",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-07.jpg?height=277&width=450&top_left_y=306&top_left_x=302"
  },
  {
    "exam": "CUET",
    "questionId": "40",
    "text": "The relative order of reactivity of $1^{\\circ}, 2^{\\circ}, 3^{\\circ}$ alcohol towards dehydration is:\n(1) $1^{\\circ}>2^{\\circ}>3^{\\circ}$\n(2) $2^{\\circ}>1^{\\circ}>3^{\\circ}$\n(3) $2^{\\circ}>3^{\\circ}>1^{\\circ}$\n(4) $3^{\\circ}>2^{\\circ}>1^{\\circ}$",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Alcohols, Phenols and Ethers",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "$1^{\\circ}>2^{\\circ}>3^{\\circ}$",
      "$2^{\\circ}>1^{\\circ}>3^{\\circ}$",
      "$2^{\\circ}>3^{\\circ}>1^{\\circ}$",
      "$3^{\\circ}>2^{\\circ}>1^{\\circ}$"
    ],
    "correctOption": "4",
    "markscheme": "Explanation: Reactivity is $3^{\\circ}>2^{\\circ}>1^{\\circ}$, because tertiary carbocation is more stable than $2^{\\circ}$ and $2^{\\circ}$ is more stable than $1^{\\circ}$ due to inductive effect of alkyl group.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "41",
    "text": "Read the passage below and answer the question: Aldehydes and Ketones, having atleast one methyl group linked to the carbonyl carbon atom (methyl Ketones), are oxidised by sodium hypohalite to sodium salts of corresponding carboxylic acids having one carbon atom less them that of carbonyl compound is converted to haloform. This oxidation does not affect carbon - carbon double bond, if present in a molecule.\n\nChoose the correct answer from the options given belowr:\n\n(1) (A)-(II), (B)-(IV), (C)-(III), (D)-(I)\n\n(2) (A)-(II), (B)-(I), (C)-(IV), (D)-(III)\n\n(3) (A)-(III), (B)-(IV), (C)-(I), (D)-(II)\n\n(4) (A)-(III), (B)-(I), (C)-(II), (D)-(IV)",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Aldehydes and Ketones",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A)-(II), (B)-(IV), (C)-(III), (D)-(I)",
      "(A)-(II), (B)-(I), (C)-(IV), (D)-(III)",
      "(A)-(III), (B)-(IV), (C)-(I), (D)-(II)",
      "(A)-(III), (B)-(I), (C)-(II), (D)-(IV)"
    ],
    "correctOption": "2",
    "markscheme": "",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-07.jpg?height=559&width=727&top_left_y=1367&top_left_x=284"
  },
  {
    "exam": "CUET",
    "questionId": "42",
    "text": "Which of the following aldehyde will give Aldol condensation:\n\n<smiles>O=Cc1ccccc1</smiles>\n\n(A)\n\n<smiles>CC(C)(C)C=O</smiles>\n\n(B)\n\n<smiles>CC(=O)Cc1ccccc1</smiles>\n\n(C)\n\n<smiles>O=C1CCCCC1</smiles>\n\n(D)\n(1) (A)\n(2) (B)\n(3) (C)\n(4) (D)",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Aldehydes and Ketones",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A)",
      "(B)",
      "(C)",
      "(D)"
    ],
    "correctOption": "4",
    "markscheme": "Explanation: cyclic hexanone undergo aldol condensation",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "43",
    "text": "Arrange in decreasing order of nuelophilic addition:\n\n(A) \\(\\mathrm{CH}_{3} \\mathrm{CHO}\\)\n\n(B) \\(\\mathrm{C}_{2} \\mathrm{H}_{5} \\mathrm{COCH}_{3}\\)\n\n(C) \\(\\mathrm{CH}_{3} \\mathrm{COCH}_{3}\\)\n\n(D) HCHO\n\nChoose the correct answer\n\n(1) (D) $>$ (A) $>$ (C) $>$ (B)\n\n(2) (D) $>$ (A) $>$ (B) $>$ (C)\n\n(3) (C) $>$ (B) $>$ (A) $>$ (D)\n\n(4) (B) $>$ (C) $>$ (A) $>$ (D)",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Aldehydes and Ketones",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(D) > (A) > (C) > (B)",
      "(D) > (A) > (B) > (C)",
      "(C) > (B) > (A) > (D)",
      "(B) > (C) > (A) > (D)"
    ],
    "correctOption": "1",
    "markscheme": "Explanation: The reactivity of nucleophilic addidtion in carbonyl compound decreases with increse in electron density on carbonyl carbon. The inductive effect increase the electron density on carbonyl carbon atoms. Hence, +I effect is \\(\\mathrm{HCHO}<\\mathrm{CH}_{3} \\mathrm{CHO}<\\mathrm{CH}_{3} \\mathrm{COCH}_{3}<\\mathrm{C}_{2} \\mathrm{H}_{5} \\mathrm{COCH}_{3}\\)",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "44",
    "text": "Which of the following statements are true?\n\n(A) \\(\\mathrm{CH}_{3} \\mathrm{CHO}\\), and \\(\\mathrm{CH}_{3} \\mathrm{CH}_{2} \\mathrm{CHO}\\) can be distinguished by Tollen's test.\n\n(B) \\(\\mathrm{CH}_{3} \\mathrm{CH}_{2} \\mathrm{CHO}\\) and \\(\\mathrm{CH}_{3} \\mathrm{COCH}_{3}\\) can be distinguished by Fehling's test.\n\n(C) \\(\\mathrm{CH}_{3} \\mathrm{CHO}\\) CHO can be distinguished by Fehling's test.\n\n(D) \\(\\mathrm{HCHO}, \\mathrm{CH}_{3} \\mathrm{CHO}\\) can be distinguished by \\(\\mathrm{NaHCO}_{3}\\) test.\n\n(E) \\(\\mathrm{HCOOH}, \\mathrm{CH}_{3} \\mathrm{COOH}\\) can be distinguished by \\(\\mathrm{NaHCO}_{3}\\) test.\n\nChoose the correct answer from the options given below:\n(1) (A), (B) only\n(2) (B), (C) only\n(3) (C), (D) only\n(4) (E), (A) only",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Aldehydes and Ketones",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "(A), (B) only",
      "(B), (C) only",
      "(C), (D) only",
      "(E), (A) only"
    ],
    "correctOption": "2",
    "markscheme": "Explanation: Benzaldehyde and Ketones do not give Fehling's test. Ethanal and propanal both give silver mirror test and red precipitate with Fehling's solution.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "45",
    "text": "Predict the correct product (A):\n\n<smiles>O=CC=Cc1ccccc1</smiles>\n\n(1)\n\n<smiles>NNC(=O)N=CC=Cc1ccccc1</smiles>\n\n(2)\n\n<smiles>NC(=O)N=CC=Cc1ccccc1</smiles>\n\n(3)\n\n<smiles>NNC(=O)[NH2+][C@@H](O)C=CC1CCCCC1</smiles>\n\n(4)\n\n<smiles>NC(=O)NCC(N)c1ccccc1</smiles>",
    "subject": "Chemistry",
    "topic": "Organic Chemistry",
    "subtopic": "Aldehydes and Ketones",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "<smiles>NNC(=O)N=CC=Cc1ccccc1</smiles>",
      "<smiles>NC(=O)N=CC=Cc1ccccc1</smiles>",
      "<smiles>NNC(=O)[NH2+][C@@H](O)C=CC1CCCCC1</smiles>",
      "<smiles>NC(=O)NCC(N)c1ccccc1</smiles>"
    ],
    "correctOption": "2",
    "markscheme": "",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-07.jpg?height=559&width=727&top_left_y=1367&top_left_x=284"
  },
  {
    "exam": "CUET",
    "questionId": "46",
    "text": "The accumulation of molecular species at the surface rather than in the bulk of a solid or liquid is termed as adsorption. There are two types of adsorption. In physiorsorption, attractive forces are mainly Van der Waals while in chemical adsorption adsorbate is held with chemical bonds adsorbent. Adsorption increases with increase in pressure and decreases as temperature is increased.\n\nAdsorption is spontaneous because:\n\n(1) \\(\\Delta \\mathrm{S}\\) is - ve and is more than \\(\\Delta \\mathrm{H}\\)\n\n(2) \\(\\Delta S\\) is + ve and is more than \\(\\Delta \\mathrm{H}\\)\n\n(3) \\(\\Delta \\mathrm{H}\\) is - ve and is more than \\(\\mathrm{T} \\Delta \\mathrm{S}\\)\n\n(4) \\(\\Delta \\mathrm{H}-\\Delta \\mathrm{S}\\)",
    "subject": "Chemistry",
    "topic": "Surface Chemistry",
    "subtopic": "Adsorption",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "\\(\\Delta \\mathrm{S}\\) is - ve and is more than \\(\\Delta \\mathrm{H}\\)",
      "\\(\\Delta S\\) is + ve and is more than \\(\\Delta \\mathrm{H}\\)",
      "\\(\\Delta \\mathrm{H}\\) is - ve and is more than \\(\\mathrm{T} \\Delta \\mathrm{S}\\)",
      "\\(\\Delta \\mathrm{H}-\\Delta \\mathrm{S}\\)"
    ],
    "correctOption": "3",
    "markscheme": "Explanation: For a spontaneous reaction \\(\\Delta \\mathrm{H}\\) is always -ve and it is more than \\(\\mathrm{T} \\Delta \\mathrm{S}\\).",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "47",
    "text": "Which of the following is not characteristic of chemical adsorption?\n(1) It is irreversible\n\n(2) It is highly specific\n\n(3) High temperature is favourable\n\n(4) It results into multi molecular layers",
    "subject": "Chemistry",
    "topic": "Surface Chemistry",
    "subtopic": "Adsorption",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "It is irreversible",
      "It is highly specific",
      "High temperature is favourable",
      "It results into multi molecular layers"
    ],
    "correctOption": "4",
    "markscheme": "Explanation:Chemical adsorption do not results into multi molecular layers which is not a characteristics of chemical adsorption while all others are characteristics of chemical adsorption.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "48",
    "text": "Which of the following is not an application of adsorption?\n\n(1) Control of humidity using silica gel\n\n(2) Separation of noble gases using charcoal\n\n(3) Removal of colouring matter from solutions\n\n(4) Inversion of cane sugar using mineral acids as catalysts",
    "subject": "Chemistry",
    "topic": "Surface Chemistry",
    "subtopic": "Adsorption",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "Control of humidity using silica gel",
      "Separation of noble gases using charcoal",
      "Removal of colouring matter from solutions",
      "Inversion of cane sugar using mineral acids as catalysts"
    ],
    "correctOption": "4",
    "markscheme": "Explanation: Adsorption is not applicable in inversion of cane sugar using mineral acids as catalyst while all others are application of adsorption.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "49",
    "text": "For Freundlich isotherm, graph of \\(\\log (x / \\mathrm{m})\\) is plotted against \\(\\log \\mathrm{Y}\\). The slope of line and its Y axis intercepts respectively are:\n(1) \\(\\frac{1}{\\mathrm{n}}, \\mathrm{K}\\)\n(2) \\(\\frac{1}{\\mathrm{n}}, \\log \\mathrm{K}\\)\n(3) \\(\\mathrm{n}, 1 / \\mathrm{K}\\)\n(4) \\(\\mathrm{n}, \\frac{1}{\\log \\mathrm{K}}\\)",
    "subject": "Chemistry",
    "topic": "Surface Chemistry",
    "subtopic": "Adsorption",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "\\(\\frac{1}{\\mathrm{n}}, \\mathrm{K}\\)",
      "\\(\\frac{1}{\\mathrm{n}}, \\log \\mathrm{K}\\)",
      "\\(\\mathrm{n}, 1 / \\mathrm{K}\\)",
      "\\(\\mathrm{n}, \\frac{1}{\\log \\mathrm{K}}\\)"
    ],
    "correctOption": "2",
    "markscheme": "",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_07_20_144493cbe99c8920f625g-08.jpg?height=459&width=716&top_left_y=1477&top_left_x=1129"
  },
  {
    "exam": "CUET",
    "questionId": "50",
    "text": "Critical temperature of few gases are given \\(\\mathrm{SO}_{2}\\) \\((630 \\mathrm{~K}), \\mathrm{CH}_{4},(190 \\mathrm{~K}), \\mathrm{H}_{2}\\) (33K). What is the correct order of case of physisorption of these gases?\n(1) \\(\\mathrm{CH}_{4}>\\mathrm{H}_{2}>\\mathrm{SO}_{2}\\)\n(2) \\(\\mathrm{SO}_{2}>\\mathrm{CH}_{4}>\\mathrm{H}_{2}\\)\n(3) \\(\\mathrm{H}_{2}>\\mathrm{CH}_{4}>\\mathrm{SO}_{2}\\)\n(4) \\(\\mathrm{H}_{2}>\\mathrm{SO}_{2}>\\mathrm{CH}_{4}\\)",
    "subject": "Chemistry",
    "topic": "Surface Chemistry",
    "subtopic": "Adsorption",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
      "\\(\\mathrm{CH}_{4}>\\mathrm{H}_{2}>\\mathrm{SO}_{2}\\)",
      "\\(\\mathrm{SO}_{2}>\\mathrm{CH}_{4}>\\mathrm{H}_{2}\\)",
      "\\(\\mathrm{H}_{2}>\\mathrm{CH}_{4}>\\mathrm{SO}_{2}\\)",
      "\\(\\mathrm{H}_{2}>\\mathrm{SO}_{2}>\\mathrm{CH}_{4}\\)"
    ],
    "correctOption": "2",
    "markscheme": "Explanation: physisorption of gases depends upon the nature of gas and its liquification at critical temperature. Lower the value of critical temperature, lesser will be adsorption. \\(\\mathrm{H}_{2}\\) has low value 33 K , \\(\\mathrm{CH}_{4}\\) has 190 K and \\(\\mathrm{SO}_{2}\\) has 630 K .",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  }
];


async function main() {
  for (const question of questions) {
    await prisma.question.create({
      data: {
        questionId: question.questionId,
        text: question.text,
        subject: question.subject,
        topic: question.topic,
        subtopic: question.subtopic,
        difficulty: question.difficulty,
        type: question.type,
        year: parseInt(question.year, 10),
        reviewed: question.reviewed,
        completed: question.completed,
        options: question.options,
        correctOption: question.correctOption,
        markscheme: question.markscheme,
        exam: question.exam,
        marks: question.marks,
        correctAttempts: question.correctAttempts,
        wrongAttempts: question.wrongAttempts,
        averageTimeTaken: question.averageTimeTaken,
        lastAttempted: question.lastAttempted ? new Date(question.lastAttempted) : null,
        diagramUrl: question.diagramUrl,  // Add this line
      },
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
