const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const questions = [
  {
    "exam": "CUET",
    "questionId": "601",
    "text": "Select the organism which does not undergoes parthenogenesis.",
    "subject": "Biology",
    "topic": "Reproduction in Organisms",
    "subtopic": "Parthenogenesis",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Honeybee", "Rotifer", "Turkey", "Fruit fly"],
    "correctOption": "D",
    "markscheme": "Parthenogenesis is development of an egg into a complete individual without fertilisation. It occurs commonly among lower plants and invertebrate animals (particularly rotifers, aphids, ants, wasps, and bees) and rarely among higher vertebrates.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "602",
    "text": "The method of producing thousands of plants through tissue culture is called as:",
    "subject": "Biology",
    "topic": "Biotechnology",
    "subtopic": "Plant Tissue Culture",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Somaclones", "Micro-propagation", "Somatic hybridisation", "Vegetative propagation"],
    "correctOption": "B",
    "markscheme": "Micro propagation, also known as plant tissue culture, is the technique used for rapid vegetative multiplication of plants by using explants (living tissue or cells of a plant). Through this process, a large number of plants can be produced in a short span of time.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "603",
    "text": "Which of the following statements are correct regarding decomposition? A. Decomposition is largely oxygen-requiring process. B. The rate of decomposition is controlled by chemical composition of detritus and climatic factors. C. Dry and cold environment favour the decomposition. D. If detritus is rich in lignin and chitin, the decomposition rate is faster. Choose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Ecology",
    "subtopic": "Decomposition",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["A and B only", "C and D only", "B and C only", "A and D only"],
    "correctOption": "A",
    "markscheme": "Decomposition is the process in which complex organic matter breaks down into inorganic substances like carbon dioxide, water and nutrients. It is largely an oxygen requiring process. The rate of decomposition is controlled by the chemical composition of detritus and climatic factors. It is slower if detritus is rich in lignin and chitin and quicker if detritus is rich in nitrogen and water soluble substances like sugars.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "604",
    "text": "Identify the organism which is a source of single cell protein and is grown on commercial scale.",
    "subject": "Biology",
    "topic": "Microbes in Human Welfare",
    "subtopic": "Single Cell Protein",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Azotobacter", "Rhizobium", "Azospirillum", "Spirulina"],
    "correctOption": "D",
    "markscheme": "Microbes like Spirulina can be grown easily on material like waste material. They are being grown on an industrial scale as a source of good protein. It is used as a single celled protein.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "605",
    "text": "Match List I with List II:\\n\\n\\(\\begin{array}{|c|l|c|l|} \\hline \\text{A} & \\text{Wheat} & \\text{I} & \\text{Perisperm} \\\\ \\text{B} & \\text{Black pepper} & \\text{II} & \\text{Polyembryony} \\\\ \\text{C} & \\text{Cashew} & \\text{III} & \\text{Albuminous seed} \\\\ \\text{D} & \\text{Citrus} & \\text{IV} & \\text{False fruits} \\\\ \\hline \\end{array}\\)\\n\\nChoose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Botany",
    "subtopic": "Reproductive Structures",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["A-III, B-II, C-I, D-IV", "A-II, B-I, C-III, D-IV", "A-III, B-I, C-IV, D-II", "A-I, B-II, C-IV, D-III"],
    "correctOption": "C",
    "markscheme": "Wheat is an albuminous seed, which have endosperm with persistent stores of nutrients. Perispermic seeds are seen in black pepper and beetroot. False fruits are seen in apple, strawberry and cashew nut whereas polyembryony is seen in Citrus and Mango.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "606",
    "text": "Arrange the following events in correct sequence: A. Formation of zygote B. Formation of blastocyst C. Implantation D. Formation of morula Choose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Human Reproduction",
    "subtopic": "Embryonic Development",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["A, D, B, E", "A, B, D, C", "A, B, C, D", "C, D, B, A"],
    "correctOption": "A",
    "markscheme": "During fertilisation, the sperm and egg unite in one of the fallopian tubes to form a zygote. Then the zygote travels down the fallopian tube, where it becomes a morula. Once it reaches the uterus, the morula becomes a blastocyst. The blastocyst then burrows into the uterine lining by a process called implantation. Hence, the correct sequence of events is: Formation of zygote → Formation of Morula → Formation of blastocyst → Implantation.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "607",
    "text": "Which of the following is used to make the bacterial cell as 'Competent cell' to take up DNA?",
    "subject": "Biotechnology",
    "topic": "Genetic Engineering",
    "subtopic": "Transformation in Bacteria",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Carbonate ion", "Calcium ion", "Sodium ion", "Sulphate ion"],
    "correctOption": "B",
    "markscheme": "In order to make the bacterial cells competent, they are first treated with a specific concentration of a divalent cation, such as calcium. It increases the efficiency with which DNA enters the bacterium through pores in its cell wall.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "608",
    "text": "Identify the equation representing logistic growth of a population.",
    "subject": "Biology",
    "topic": "Ecology",
    "subtopic": "Population Growth",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["\\(\\frac{dN}{dt}=r N\\left(\\frac{K-N}{K}\\right)\\)", "\\(\\frac{dN}{dt}=r N\\)", "\\(\\frac{dN}{dt}=N\\left(\\frac{N-K}{K}\\right)\\)", "\\(\\frac{dt}{dN}=r N\\)"],
    "correctOption": "A",
    "markscheme": "The logistic growth curve, which is J-shaped, shows population growth when resources are limited. Carrying capacity is the maximum size of the population of a species that a certain environment can support for an extended period of time. The logistic growth equation can be given as \\(\\frac{dN}{dt}=rN\\left(\\frac{K-N}{K}\\right)\\). Here, r= the intrinsic rate of growth, N= the number of organisms in a population, and K= the carrying capacity.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "609",
    "text": "Early Greek thinkers thought that units of life called spores were transferred to different planets including earth. Identify the term associated with the above.",
    "subject": "Biology",
    "topic": "Evolution",
    "subtopic": "Origin of Life",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Abiogenesis", "Panspermia", "Spontaneous generation", "Biogenesis"],
    "correctOption": "B",
    "markscheme": "According to early Greek thinkers, units of life were called panspermia. They assumed that these panspermias were transferred to different planets including earth, which resulted in life.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "610",
    "text": "In gel electrophoresis the separated DNA fragments can be visualised :",
    "subject": "Biotechnology",
    "topic": "Genetic Engineering",
    "subtopic": "DNA Isolation and Visualisation",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["In visible light", "In visible light with staining", "In UV radiation without staining", "In UV radiation after staining with ethidium bromide"],
    "correctOption": "D",
    "markscheme": "Agarose gel electrophoresis is used to segregate DNA fragments according to the mass and size. The separated DNA fragments can be visualised only after staining the DNA with a compound known as ethidium bromide followed by exposure to UV radiation. We cannot see pure DNA fragments in the visible light and without staining.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "611",
    "text": "Match List I with List II: \\n\\n\\(\\begin{array}{|l|l|l|l|} \\hline \\text{A.} & \\text{Tubectomy} & \\text{I.} & \\text{Barrier method} \\\\ \\text{B.} & \\text{Copper ions} & \\text{II.} & \\text{Surgical method of sterilisation in human male.} \\\\ \\text{C.} & \\text{Cervical cap} & \\text{III.} & \\text{Surgical method of sterilisation in human female.} \\\\ \\text{D.} & \\text{Vasectomy} & \\text{IV.} & \\text{Suppress motility of sperms} \\\\ \\hline \\end{array}\\)\\n\\nChoose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Human Reproduction",
    "subtopic": "Contraception",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["A-III, B-IV, C-I, D-II", "A-III, B-I, C-IV, D-II", "A-II, B-I, C-IV, D-III", "A-IV, B-II, C-III, D-I"],
    "correctOption": "A",
    "markscheme": "Tubectomy is the sterilisation procedure in females. In this, a small part of the fallopian tube is removed or tied up through a small incision in the abdomen or through vagina.\\nCopper releasing IUDs, namely Cu-T, Cu-7 release copper that suppress the sperm motility which in turn reduces its fertilising capacity. Cervical cap is a barrier method of contraception which prevents conception by blocking the entry of sperms through the cervix.\\nVasectomy is the sterilisation procedure in males. In this, a small part of the vas deferens is removed or tied up through a small incision on the scrotum.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "612",
    "text": "Mammals are able to survive in Antarctica or in the Sahara desert as they are:",
    "subject": "Biology",
    "topic": "Ecology",
    "subtopic": "Adaptations",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Conformers", "Partial regulators", "Regulators", "Migrants"],
    "correctOption": "C",
    "markscheme": "Mammals are able to survive in Antarctica or in Sahara desert as they are regulators. Evolutionary biologists believe that the success of mammals is largely due to their ability to maintain a constant body temperature and thrive whether they live in Antarctica or in the Sahara desert.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "613",
    "text": "Match List I with List II:\\n\\n\\(\\begin{array}{|l|l|l|l|} \\hline \\text{A.} & \\text{Down's syndrome} & \\text{I.} & \\text{44+XXY} \\\\ \\text{B.} & \\text{Thalassemia} & \\text{II.} & \\text{Autosomal recessive trait} \\\\ \\text{C.} & \\text{Klinefelter's syndrome} & \\text{III.} & \\text{44+XO} \\\\ \\text{D.} & \\text{Turner's Syndrome} & \\text{IV.} & \\text{45+XY/XX} \\\\ \\hline \\end{array}\\)\\n\\nChoose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Genetics",
    "subtopic": "Genetic Disorders",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["A-IV, B-II, C-III, D-I", "A-IV, B-II, C-I, D-III", "A-I, B-III, C-IV, D-II", "A-II, B-IV, C-III, D-I"],
    "correctOption": "B",
    "markscheme": "Down's syndrome is a genetic disorder which arises due to the presence of an extra chromosome number 21 in every cell of the body. So, 47 chromosomes are present instead of the normal number 46. Thalassemia is an inherited autosomal recessive disease resulting from mutations in the α - and β-globin gene clusters on chromosome 16 and chromosome 11, respectively. Klinefelter's syndrome (sometimes called XXY) is where boys and men are born with an extra X chromosome. Turner's syndrome, a condition that affects only females, results when one of the X chromosomes (sex chromosomes) is missing or partially missing.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "614",
    "text": "Match List I with List II:\\n\\n\\(\\begin{array}{|l|l|c|l|} \\hline \\text{A.} & \\text{Heroin} & \\text{I.} & \\text{Tobacco plant} \\\\ \\text{B.} & \\text{Cannabinoids} & \\text{II.} & \\text{Erythroxvium coca} \\\\ \\text{C.} & \\text{Cocaine} & \\text{III.} & \\text{Cannabis sativa} \\\\ \\text{D.} & \\text{Nicotine} & \\text{IV.} & \\text{Papaver somniferum} \\\\ \\hline \\end{array}\\)\\n\\nChoose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Human Health and Diseases",
    "subtopic": "Drugs and Alcohol Abuse",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["A-I, B-II, C-III, D-IV", "A-II, B-I, C-III, D-IV", "A-I, B-II, C-IV, D-III", "A-IV, B-III, C-II, D-I"],
    "correctOption": "D",
    "markscheme": "Heroin is an opium derivative. Opium is obtained from dried latex of unripe capsules of Poppy plant (Papavar somniferum). Natural cannabinoids are obtained from Cannabis sativa (Hemp plant). Cocaine is obtained from coca plant, Erythroxylum coca.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "615",
    "text": "Methanogens do not produce :",
    "subject": "Biology",
    "topic": "Microbes in Human Welfare",
    "subtopic": "Methanogenesis",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Carbon dioxide and methane", "Methane and Hydrogen", "Hydrogen and Carbon dioxide", "Nitrogen and Oxygen"],
    "correctOption": "D",
    "markscheme": "Methanogens are the microorganisms that produce methane, hydrogen sulphide and carbon dioxide in their metabolic reactions.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "616",
    "text": "The correct sequence of steps involved in polymerase chain reaction (PCR) are: A. DNA polymerase is used to extends the primers using oligonucleotides. B. Desired DNA fragments are denatured. C. Amplified fragments are ligated with the vector for cloning. D. Oligonucleotides are added. Choose the correct answer from the options given below:",
    "subject": "Biotechnology",
    "topic": "Genetic Engineering",
    "subtopic": "Polymerase Chain Reaction (PCR)",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["C, A, B, D", "A, C, B, D", "A, D, B, C", "B, D, A, C"],
    "correctOption": "D",
    "markscheme": "Each cycle has three steps: Denaturation, primer annealing and extension of primers.\\nDenaturation: The double stranded DNA molecules are heated to a high temperature \\(94^{\\circ}C\\) so that the two strands separate into a single stranded DNA molecule. This process is called denaturation. Each strand acts as template for DNA synthesis.\\nAnnealing: In this step, the two oligonucleotide primers anneal (hybridize) to each of the single stranded DNA template, since, the sequence of the primers is complementary to the \\(3^{\\prime}\\) ends of the template DNA. This step is carried out at a lower temperature depending on the length and sequence of the primers. This results in the duplication of the original DNA molecule.\\nExtension of primers: DNA polymerase (Taq polymerase) extends the primers using the nucleotides provided in the reaction. The optimum temperature for this polymerization step is \\(72^{\\circ}C\\).\\nThis process is repeated over several cycles to obtain multiple copies of rDNA fragment.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "617",
    "text": "Select the correct statement/s from the following: A. Spermatogonia always undergo meiotic cell division. B. Primary spermatocytes divide by mitotic cell division. C. Secondary spermatocytes have 23 chromosomes and undergo second meiotic division. D. Spermatozoa are transformed into spermatids. Choose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Human Reproduction",
    "subtopic": "Spermatogenesis",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["A and C only", "C only", "D only", "B and C only"],
    "correctOption": "B",
    "markscheme": "Statement C is correct. Spermatogonia are diploid cells on the inside wall of seminiferous tubules that multiply by mitotic divisions. Some of the spermatogonia called primary spermatocyte undergo meiosis-I to give rise to secondary spermatocytes, which are haploid. Each secondary spermatocyte undergoes meiosis-II to give rise to two haploid spermatids which are transferred to spermatozoa by spermiogenesis.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "618",
    "text": "Which of the following metal can not be recovered from manual recycling process of e-wastes ?",
    "subject": "Biology",
    "topic": "Environmental Issues",
    "subtopic": "E-Waste Management",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Gold", "Mercury", "Copper", "Nickel"],
    "correctOption": "B",
    "markscheme": "E wastes are electronic wastes that generally include electronic goods such as computers etc. Such wastes are rich in metals such copper, iron, silicon, gold etc. These metals are highly toxic and pose serious health hazards. Recycling is the only solution for the treatment of e-waste, provided it is carried out in an environment friendly manner.\\nHowever toxicants such as asbestos, lead, mercury etc. cannot be recovered from manual recycling process of e-wastes.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "619",
    "text": "Bt toxin produced by Bacillus thuringiensis is resistant to :",
    "subject": "Biology",
    "topic": "Biotechnology",
    "subtopic": "Genetically Modified Organisms",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Drought", "Insects", "Nematodes", "Viruses"],
    "correctOption": "B",
    "markscheme": "Some strains of Bacillus thuringiensis have proteins that kill insects like coleopterans (beetles), lepidopterans (tobacco budworm, armyworm) and dipterans (flies, mosquitoes etc). Bacillus thuringiensis forms protein crystals during a particular phase of their growth. These crystals contain a toxic insecticidal protein. These proteins are present in inactive protoxin form, but become active toxin in the alkaline pH of insect gut. The activated toxin binds to the surface of midgut epithelial cells and creates pores that cause cell swelling and lysis and eventually cause death of the insect.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
  {
    "exam": "CUET",
    "questionId": "620",
    "text": "In some organisms, male has ZZ chromosomes and female has ZW chromosomes. This type of sex determination is found in :",
    "subject": "Biology",
    "topic": "Genetics",
    "subtopic": "Sex Determination",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Drosophila", "Hen", "Cockroach", "Snail"],
    "correctOption": "B",
    "markscheme": "Sex determination in birds and some reptiles is of ZW-ZZ types in which females are heteromorphic (ZW) and males have homomorphic sex chromosomes (ZZ).",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
  },
    {
        "exam": "CUET",
        "questionId": "621",
        "text": "The organisation set up by the Indian Government to take decisions regarding the validity of GM research and the safety of introducing GM organisms is:",
        "subject": "Biology",
        "topic": "Biotechnology",
        "subtopic": "Regulation of Biotechnology",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["Genetic Engineering Approval Committee (GEAC)", "Genetic Modification Approval Committee (GMAC)", "Indian Council of Agricultural Research (ICAR)", "All India Institute of Medical Sciences (AIIMS)"],
        "correctOption": "A",
        "markscheme": "Indian Government has set up organisations like GEAC (Genetic Engineering Approval Committee), which make decisions about the validity of GM research and the safety of GM organisms for public services.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "622",
        "text": "Which of the following is a hormone releasing IUD?",
        "subject": "Biology",
        "topic": "Reproductive Health",
        "subtopic": "Contraceptive Methods",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["Multiload 375", "LNG-20", "Cervical Cap", "Vault"],
        "correctOption": "B",
        "markscheme": "LNG-20 is a hormone releasing IUDs, which makes the uterus unsuitable for implantation and the cervix hostile to the sperms.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "623",
        "text": "The puffed up appearance of dough is due to the production of:",
        "subject": "Biology",
        "topic": "Microbes in Human Welfare",
        "subtopic": "Microbes in Household Products",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["Oxygen gas", "CO2 gas", "Ethyl alcohol", "Pyruvic acid"],
        "correctOption": "B",
        "markscheme": "The dough, which is used for making bread, is fermented by using baker's yeast (Saccharomyces cerevisiae). The puffed up appearance of dough is due to the production of CO2 gas.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "624",
        "text": "Select the statements which do not hold true for Cancer:",
        "subject": "Biology",
        "topic": "Human Health and Disease",
        "subtopic": "Cancer",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["A. Cancerous cells show a property of contact inhibition.", "B. Metastasis is the most feared property of malignant tumors.", "C. Malignant tumor cells invade and damage the surrounding tissue.", "D. Malignant tumor cells grow slowly."],
        "correctOption": "C",
        "markscheme": "Cancerous cells appear to have lost the property of contact inhibition. They just continue to divide giving rise to masses of cells called tumors. Malignant tumors are the mass of proliferating cells called neoplastic or tumor cells. These cells grow very rapidly and invade and damage surrounding tissues.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
    "exam": "CUET",
    "questionId": "625",
    "text": "Select the statements which do not hold true for Cancer:\\n\\nA. Cancerous cells show a property of contact inhibition.\\n\\nB. Metastasis is the most feared property of malignant tumors.\\n\\nC. Malignant tumor cells invade and damage the surrounding tissue.\\n\\nD. Malignant tumor cells grows slowly.",
    "subject": "Biology",
    "topic": "Human Health and Disease",
    "subtopic": "Cancer",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["A and B only", "B and C only", "A and D only", "B and D only"],
    "correctOption": "C",
    "markscheme": "Cancer is an abnormal and uncontrolled multiplication of cells resulting in the formation of tumor. Cancerous cells appear to have lost the property of contact inhibition. They just continue to divide giving rise to masses of cells called tumors. Tumors are of two types: Benign tumors remain confined to the place of their origin and cause little damage, while malignant tumors are the mass of proliferating cells called neoplastic or tumor cells. These cells grow very rapidly and invade and damage surrounding tissues.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
    {
        "exam": "CUET",
        "questionId": "626",
        "text": "Mature mRNA is a fully processed:",
        "subject": "Biology",
        "topic": "Molecular Biology",
        "subtopic": "RNA Processing",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["hnRNA", "snRNA", "28S RNA", "5S rRNA"],
        "correctOption": "A",
        "markscheme": "Mature mRNA is the completely processed mRNA molecule in the cell of eukaryotes. The mRNA is a type of RNA involved in protein synthesis.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "627",
        "text": "Which forest is also known as the 'lungs of the planet earth'?",
        "subject": "Biology",
        "topic": "Ecology",
        "subtopic": "Forests",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["Amazon rain forest", "Rain forest of north-east India", "Tiaga forest", "Tundra forest"],
        "correctOption": "A",
        "markscheme": "The Tropical rainforest of Amazon is known as the lungs of the planet earth because they are responsible for the production of about 20% of the earth's oxygen. They remove a large amount of carbon dioxide from the air and give out oxygen.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "628",
        "text": "Inbreeding is carried out in animal husbandry because it:",
        "subject": "Biology",
        "topic": "Animal Husbandry",
        "subtopic": "Inbreeding",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["Increase hybrid vigour", "Improves the breed", "Increase heterozygosity", "Increase homozygosity"],
        "correctOption": "D",
        "markscheme": "Inbreeding is the mating of more closely related individuals within the same breed for 4-6 generations. It is carried out in animal husbandry because it increases homozygosity to evolve a pure line animal.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "629",
        "text": "Which is known as 'Terror of Bengal'?",
        "subject": "Biology",
        "topic": "Biodiversity",
        "subtopic": "Invasive Species",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["Water Lilly", "Hydrilla", "Water hyacinth", "Lantana"],
        "correctOption": "C",
        "markscheme": "Water hyacinth is known as the terror of Bengal. It is an exotic shrub which is growing at an alarming rate on the surface of water bodies. It inhibits the growth of fish and other aquatic organisms due to cut down of light and lack of oxygen. It is also an example of loss of biodiversity due to alien species invasion.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "630",
        "text": "Threatened animals and plants are taken out from their natural habitat and placed in special settings, protected and given special care is:",
        "subject": "Biology",
        "topic": "Conservation Biology",
        "subtopic": "Ex Situ Conservation",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["In situ conservation", "Ex situ conservation", "Conservation in national park", "Conservation in biospheres"],
        "correctOption": "B",
        "markscheme": "Ex situ conservation (off site) is the method of conservation in which threatened species of plants and animals are taken out of their habitats and are kept in special settings such as genetic resource centres, zoological parks, botanical gardens, gene banks.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
    "exam": "CUET",
    "questionId": "631",
    "text": "Match List I with List II: \\n\\n\\(\\begin{array}{|ll|ll|} \\hline \\text{List - I} & & \\text{List - II} & \\\\ \\hline \\text{(A)} & \\text{Dominant trait of pod colour in garden pea.} & \\text{(I)} & \\text{Polygenic traits} \\\\ \\text{(B)} & \\text{The physical association of two genes on a chromosome.} & \\text{(II)} & \\text{Pleiotropy} \\\\ \\text{(C)} & \\text{The traits generally controlled by three or more genes.} & \\text{(III)} & \\text{Yellow} \\\\ \\text{(D)} & \\text{When a single gene exhibits multiple phenotypic expressions.} & \\text{(IV)} & \\text{Linkage} \\\\ \\hline \\end{array}\\)\\n\\nChoose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Genetics",
    "subtopic": "Linkage and Polygenic Traits",
    "difficulty": "Medium",
    "type": "Matching",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
        "(A)-(V), (B)-(IV), (C)-(I), (D)-(II)",
        "(A)-(III), (B)-(II), (C)-(I), (D)-(IV)",
        "(A)-(II), (B)-(III), (C)-(V), (D)-(I)",
        "(A)-(III), (B)-(II), (C)-(I), (D)-(IV)"
    ],
    "correctOption": "D",
    "markscheme": "Green pod colour was dominant to yellow in garden pea. Linkage is defined as the co-existence of two or more genes on the same chromosome. If the genes are situated on the same chromosome and lie close to each other, then they are inherited together and are said to be linked genes. Pleiotropy is the ability of a gene to have multiple phenotypic effects as it influences a number of characters simultaneously. Polygenic inheritance occurs when one characteristic is controlled by two or more genes. Inheritance of skin pigmentation is an example of polygenic inheritance.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
    {
    "exam": "CUET",
    "questionId": "632",
    "text": "Sequence the following steps in formation of female gametophyte of flowering plants:\\n\\nA. Cell walls are laid down.\\n\\nB. Formation of seven cells with eight nuclei.\\n\\nC. Meiosis in megaspore mother cell and formation of megaspore tetrad.\\n\\nD. Functional megaspore undergoes three mitotic divisions, results in formation of eight nuclei.",
    "subject": "Biology",
    "topic": "Reproduction in Flowering Plants",
    "subtopic": "Gametophyte Development",
    "difficulty": "Medium",
    "type": "Sequencing",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
        "A-D-C-B",
        "C-D-A-B",
        "C-A-B-D",
        "A-C-B-D"
    ],
    "correctOption": "B",
    "markscheme": "The megaspore mother cell (MMC) undergoes meiotic division to produce four megaspores. In a majority of flowering plants, only one megaspore is functional while the other three degenerate. The single functional megaspore develops into the female gametophyte.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
    {
        "exam": "CUET",
        "questionId": "633",
        "text": "In which process unusual nucleotide (methyl guanosine triphosphate) is added to the 5' end of hnRNA?",
        "subject": "Biology",
        "topic": "Molecular Biology",
        "subtopic": "RNA Processing",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["Splicing", "Capping", "Tailing", "Transcription factor"],
        "correctOption": "B",
        "markscheme": "Capping is the process in which an unusual nucleotide called methyl guanosinetriphosphate (cap) is added to the 5' end of hnRNA. Tailing (Polyadenylation) is the process in which adenylate residues (200-300) are added at 3' end of hnRNA in a template independent manner.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "634",
        "text": "Select the incorrect statements given below.",
        "subject": "Biology",
        "topic": "Environmental Issues",
        "subtopic": "Pollution and Conservation",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["A. Methane and Carbon dioxide are green house gases.", "B. The Montreal Protocol is associated with the control of emission of ozone depleting substances.", "C. Use of incinerators is not crucial to dispose off hospital wastes.", "D. Dobson units is used to measure water quality."],
        "correctOption": "C-D",
        "markscheme": "The thickness of the ozone (O3) in a column of air from the ground to the top of the atmosphere is measured in terms of Dobson units (DU). Hospital wastes contain disinfectants and other harmful chemicals, and also pathogenic micro-organisms. The incinerators are used to dispose hospital wastes.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "635",
        "text": "Biofertilisers are the organisms that enrich the nutrient quality of the soil. Which of the following is not a source of biofertiliser?",
        "subject": "Biology",
        "topic": "Biotechnology",
        "subtopic": "Biofertilizers",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["Bacteria", "Fungi", "Baculoviruses", "Cyanobacteria"],
        "correctOption": "C",
        "markscheme": "Biofertilisers are living organisms, which help increase the fertility of soil. It involves the selection of beneficial microorganisms like Bacteria, fungi, cyanobacteria etc. Baculoviruses are suitable for species-specific, narrow spectrum insecticidal applications.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
    "exam": "CUET",
    "questionId": "636",
    "text": "Match List I with List II: \\n\\n\\(\\begin{array}{|ll|ll|} \\hline \\text{List - I} & & \\text{List - II} & \\\\ \\hline \\text{(A)} & \\text{The primates with brain capacity of around 900 cc.} & \\text{(I)} & \\text{Neanderthal man} \\\\ \\text{(B)} & \\text{The primates with brain capacity of 1400 cc and lived in east and central Asia.} & \\text{(II)} & \\text{Homo erectus} \\\\ \\text{(C)} & \\text{The primates which arose in Africa and moved across continents and developed into distinct races.} & \\text{(III)} & \\text{Homo sapiens} \\\\ \\text{(D)} & \\text{The primates with the brain capacities between 650-800 cc and probably did not eat meat.} & \\text{(IV)} & \\text{Australopithecines} \\\\ \\hline \\end{array}\\)\\n\\nChoose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Evolution",
    "subtopic": "Hominid Evolution",
    "difficulty": "Medium",
    "type": "Matching",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
        "(A-II, B-I, C-III, D-IV)",
        "(A-III, B-IV, C-II, D-I)",
        "(A-I, B-III, C-IV, D-II)",
        "(A-III, B-I, C-V, D-II)"
    ],
    "correctOption": "A-II, B-I, C-III, D-IV",
    "markscheme": "Homo erectus is the primates with brain capacity of around 900 cc. Neanderthal man is the primates with brain capacity of 1400 cc, which lived in east and central Asia. Homo sapiens are the primates which arose in Africa and moved across continents and developed into distinct races. Homo habilis are the primates with the brain capacities between 650-800 cc, which probably did not eat meat.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
    {
        "exam": "CUET",
        "questionId": "637",
        "text": "Identify the gene which is effective against corn borer.",
        "subject": "Biology",
        "topic": "Biotechnology",
        "subtopic": "Bt Crops",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["cryLAc", "cryIAb", "cryIAc", "z gene"],
        "correctOption": "B",
        "markscheme": "The protein coded by gene cryIAb controls corn borer whereas the protein coded by genes cryIAc and cryIIAb control the cotton bollworms.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "638",
        "text": "Succession occurring after flood is:",
        "subject": "Biology",
        "topic": "Ecology",
        "subtopic": "Ecological Succession",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": ["Hydrarch succession", "Primary succession", "Secondary succession", "Mesarch succession"],
        "correctOption": "C",
        "markscheme": "Succession occurring after flood is called secondary succession. Successions where natural communities develop in an area that was earlier occupied by living organisms that was somehow lost are called secondary succession.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
        "exam": "CUET",
        "questionId": "639",
        "text": "Identify the statements which do not hold true for Deoxyribose Nucleic Acid.",
        "subject": "Biology",
        "topic": "Molecular Biology",
        "subtopic": "DNA Structure",
        "difficulty": "Medium",
        "type": "Multiple Choice",
        "year": "2023",
        "reviewed": false,
        "completed": false,
        "options": [
            "A. Only purine bases are present in DNA.",
            "B. Deoxyribose sugar is present.",
            "C. A nitrogenous base is linked to the 1'C pentose sugar through N-glycosidic linkage.",
            "D. Phosphate group is linked to OH of 4'C of a nucleotide."
        ],
        "correctOption": "A-D",
        "markscheme": "DNA has two purine bases: Adenine and guanine, which form hydrogen bonds with their complementary pyrimidines derivatives i.e. thymine, and cytosine, respectively. The phosphate is linked by a phosphodiester linkage to the 5' carbon of a nucleotide.",
        "marks": "4",
        "correctAttempts": "",
        "wrongAttempts": "",
        "averageTimeTaken": "",
        "lastAttempted": "",
        "diagramUrl": ""
    },
    {
    "exam": "CUET",
    "questionId": "640",
    "text": "Match List I with List II: \\n\\n\\(\\begin{array}{|ll|ll|} \\hline \\text{List - I} & & \\text{List - II} & \\\\ \\hline \\text{(A)} & \\text{Salmonella phi} & \\text{(I)} & \\text{Common Cold} \\\\ \\text{(B)} & \\text{Rhinovirus} & \\text{(II)} & \\text{Typhoid} \\\\ \\text{(C)} & \\text{Streptococcus pneumoniae} & \\text{(III)} & \\text{Malaria} \\\\ \\text{(D)} & \\text{Plasmodium vivax} & \\text{(IV)} & \\text{Pneumonia} \\\\ \\hline \\end{array}\\)\\n\\nChoose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Human Health and Disease",
    "subtopic": "Disease and Pathogens",
    "difficulty": "Medium",
    "type": "Matching",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
        "(A-II, B-IV, C-I, D-III)",
        "(A-II, B-IV, C-III, D-I)",
        "(A-II, B-I, C-IV, D-III)",
        "(A-I, B-II, C-III, D-IV)"
    ],
    "correctOption": "A-II, B-I, C-IV, D-III",
    "markscheme": "Typhoid fever is a life-threatening infection caused by the bacterium Salmonella typhi. Rhinoviruses are the most common cause of the common cold. The most common bacteria causing pneumonia is Streptococcus pneumoniae.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
{
    "exam": "CUET",
    "questionId": "641",
    "text": "Colostrum secreted by mother during initial stage of lactation provides passive immunity as it is rich in.",
    "subject": "Biology",
    "topic": "Human Health and Disease",
    "subtopic": "Immunity",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Placental lactogen", "Prolactin", "Antigen", "IgA antibodies"],
    "correctOption": "D",
    "markscheme": "The yellowish milk produced by the new mother during the initial few days of lactation is called colostrum. It contains immunoglobin A (IgA), which is essential for the newborn baby to develop resistance to various antigens.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
{
    "exam": "CUET",
    "questionId": "642",
    "text": "Which of the following is passive immunisation?",
    "subject": "Biology",
    "topic": "Human Health and Disease",
    "subtopic": "Immunity",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["injecting inactivated pathogens", "injecting antigenic preparation", "injecting preformed antibodies", "injected weakened pathogens"],
    "correctOption": "C",
    "markscheme": "Passive immunity is a type of acquired immunity in which ready-made antibodies are transferred from one individual to another. It is fast and provides immediate relief.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
{
    "exam": "CUET",
    "questionId": "643",
    "text": "Immunity provided to the foetus from the mother through placenta during pregnancy is:",
    "subject": "Biology",
    "topic": "Human Health and Disease",
    "subtopic": "Immunity",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Active immunity", "Passive immunity", "Non-specific immunity", "Innate immunity"],
    "correctOption": "B",
    "markscheme": "Immunity provided to the foetus from the mother through placenta during pregnancy is called passive immunity.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
{
    "exam": "CUET",
    "questionId": "644",
    "text": "Production of antibodies against antigens in the body is:",
    "subject": "Biology",
    "topic": "Human Health and Disease",
    "subtopic": "Immunity",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Innate immunity", "Passive immunity", "Active immunity", "Non-Specific immunity"],
    "correctOption": "C",
    "markscheme": "Production of antibodies against antigens in the body is called active immunity. It is a slow process but has long-lasting effects.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
{
    "exam": "CUET",
    "questionId": "645",
    "text": "Match List I with List II: \\n\\n\\(\\begin{array}{|ll|ll|} \\hline \\text{List - I} & & \\text{List - II} & \\\\ \\hline \\text{(A)} & \\text{Physical Barrier} & \\text{(I)} & \\text{Saliva} \\\\ \\text{(B)} & \\text{Cellular Barrier} & \\text{(II)} & \\text{Interferons} \\\\ \\text{(C)} & \\text{Physiological Barrier} & \\text{(III)} & \\text{Skin} \\\\ \\text{(D)} & \\text{Cytokine Barrier} & \\text{(IV)} & \\text{Polymorpho-nuclear leukocytes} \\\\ \\hline \\end{array}\\)\\n\\nChoose the correct answer from the options given below:",
    "subject": "Biology",
    "topic": "Human Health and Disease",
    "subtopic": "Immunity",
    "difficulty": "Medium",
    "type": "Matching",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": [
        "A-III, B-IV, C-I, D-II",
        "A-III, B-I, C-II, D-IV",
        "A-I, B-IV, C-III, D-II",
        "A-IV, B-I, C-III, D-II"
    ],
    "correctOption": "A-III, B-IV, C-I, D-II",
    "markscheme": "Skin is an example of a physical barrier. Polymorpho-nuclear leukocytes (PMNL-neutrophils) kill pathogens by phagocytosis, acting as a cellular barrier. Saliva in the mouth is an example of a physiological barrier, while virus-infected cells secrete proteins called interferons, which protect non-infected cells from the spread of viral infection, representing a cytokine barrier.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
{
    "exam": "CUET",
    "questionId": "646",
    "text": "Which of the following constitutes the first trophic level?\\n",
    "subject": "Biology",
    "topic": "Ecology",
    "subtopic": "Trophic Levels",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Plants", "Herbivores", "Carnivores", "Omnivores"],
    "correctOption": "A",
    "markscheme": "Producers always occupy the first trophic level of every food chain because only they have the ability to trap solar energy with the help of chlorophyll and synthesize their own food.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": "https://cdn.mathpix.com/cropped/2024_08_02_1b7a8226928e230adfebg-08.jpg?height=468&width=800&top_left_y=1361&top_left_x=1008"
},
{
    "exam": "CUET",
    "questionId": "647",
    "text": "Sparrow comes under which of the following categories:",
    "subject": "Biology",
    "topic": "Ecology",
    "subtopic": "Trophic Levels",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Producers", "Primary consumers", "Secondary consumers", "Tertiary consumers"],
    "correctOption": "C",
    "markscheme": "Sparrow is a primary consumer when it eats seeds, fruits, peas, and a secondary consumer when it eats insects and worms.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
{
    "exam": "CUET",
    "questionId": "648",
    "text": "Each trophic level has a certain mass of living material at a particular time called as:",
    "subject": "Biology",
    "topic": "Ecology",
    "subtopic": "Trophic Levels",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Standing crop", "Living crop", "Standing life", "Time crop"],
    "correctOption": "A",
    "markscheme": "Each trophic level has a certain mass of living material at a particular time called as the standing crop. The standing crop is measured as the mass of living organisms (biomass) or the number in a unit area. The biomass of a species is expressed in terms of fresh or dry weight.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
{
    "exam": "CUET",
    "questionId": "649",
    "text": "Which among the following is not a primary consumer?",
    "subject": "Biology",
    "topic": "Ecology",
    "subtopic": "Trophic Levels",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Snake", "Grasshopper", "Zooplankton", "Caterpillar"],
    "correctOption": "A",
    "markscheme": "Snakes are not primary consumers as they are not herbivores.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
},
{
    "exam": "CUET",
    "questionId": "650",
    "text": "Which of the following is a part of the detritus food chain?",
    "subject": "Biology",
    "topic": "Ecology",
    "subtopic": "Food Chains",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2023",
    "reviewed": false,
    "completed": false,
    "options": ["Earthworm", "Birds", "Man", "Snake"],
    "correctOption": "A",
    "markscheme": "The detritus food chain is a type of food chain that starts with dead organic matter. The earthworm acts as the primary consumer in a detritus food chain.",
    "marks": "4",
    "correctAttempts": "",
    "wrongAttempts": "",
    "averageTimeTaken": "",
    "lastAttempted": "",
    "diagramUrl": ""
}
];


async function main() {
  for (const question of questions) {
    await prisma.question.create({
      data: {
        questionId: question.questionId,
        text: question.text,
        subject: question.subject,
        topic: question.topic,
        subtopic: question.subtopic,
        difficulty: question.difficulty,
        type: question.type,
        year: parseInt(question.year, 10),
        reviewed: question.reviewed,
        completed: question.completed,
        options: question.options,
        correctOption: question.correctOption,
        markscheme: question.markscheme,
        exam: question.exam,
        marks: question.marks,
        correctAttempts: question.correctAttempts,
        wrongAttempts: question.wrongAttempts,
        averageTimeTaken: question.averageTimeTaken,
        lastAttempted: question.lastAttempted ? new Date(question.lastAttempted) : null,
        diagramUrl: question.diagramUrl,  // Add this line
      },
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
