const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const questions = [
  {
    "questionId": "501411",
    "text": "Ram and Balram are partners in a firm sharing profit and losses in the ratio of 2:1. An extract of the Balance Sheet as of 31st March 2022:\\n\\n\\(\\begin{array}{|c|c|} \\hline \\text{Liabilities} & \\text{Assets} \\\\ \\hline \\text{--} & \\text{Furniture} & 80,000 \\\\ \\hline \\end{array}\\)\\n\\nIf the value of the above furniture is overvalued by \\(33\\frac{1}{3}\\%\\), choose the value of furniture to be shown in the new Balance Sheet out of the following:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["₹ 1,06,667", "₹ 60,000", "₹ 1,00,000", "₹ 26,667"],
    "correctOption": "B",
    "markscheme": "Calculate the overvaluation percentage: \\(33\\frac{1}{3}\\% = \\frac{100}{3}\\%\\)\\nFind the correct value of the furniture: Let the correct value of the furniture be \\(X\\).\\nIf \\(X\\) is the correct value, the overvalued amount is \\(X \\times \\frac{100}{3}\\% = \\frac{X}{3}\\).\\nThe given overvalued furniture value is \\(₹ 80,000\\), which is \\(X + \\frac{X}{3}\\):\\n\\(80,000 = X + \\frac{X}{3}\\)\\n\\(80,000 = \\frac{3X + X}{3}\\)\\n\\(80,000 = \\frac{4X}{3}\\)\\n\\(X = \\frac{80,000 \\times 3}{4}\\)\\n\\(X = 60,000\\)"
  },
  {
    "questionId": "501412",
    "text": "The balance sheet of a partnership firm showed Motor Vehicles at ₹ 1,50,000. After the admission of a partner, the motor vehicles were revalued at ₹ 1,80,000. How should this be recorded in the Revaluation Account?",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["Debit Revaluation Account ₹ 30,000", "Credit Revaluation Account ₹ 30,000", "Debit Revaluation Account ₹ 1,80,000", "Credit Revaluation Account ₹ 1,80,000"],
    "correctOption": "B",
    "markscheme": "Motor Vehicles are revalued upwards from \\(₹ 1,50,000\\) to \\(₹ 1,80,000\\).\\nThe increase in value is \\(₹ 1,80,000 - ₹ 1,50,000 = ₹ 30,000\\).\\nWhen an asset is revalued upwards, the increase is credited to the Revaluation Account."
  },
  {
    "questionId": "501413",
    "text": "A and B are partners sharing profits and losses equally. They admit C into partnership with 1/4th share in profits. C acquires his share equally from A and B. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["1:1:2", "3:3:2", "2:2:1", "3:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of A and B is 1:1.\\nC's share is 1/4th, and he acquires it equally from A and B, so each gives up \\(\\frac{1}{8}\\).\\nNew ratio:\\n\\(A's\\ new\\ share = \\frac{1}{2} - \\frac{1}{8} = \\frac{4}{8} - \\frac{1}{8} = \\frac{3}{8}\\)\\n\\(B's\\ new\\ share = \\frac{1}{2} - \\frac{1}{8} = \\frac{4}{8} - \\frac{1}{8} = \\frac{3}{8}\\)\\n\\(C's\\ share = \\frac{1}{4} = \\frac{2}{8}\\)\\nNew profit-sharing ratio is 3:3:2."
  },
  {
    "questionId": "501414",
    "text": "X and Y are partners sharing profits in the ratio of 3:2. They admit Z into the partnership. X gives 1/3rd of his share and Y gives 1/4th of his share to Z. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["3:2:1", "7:5:4", "6:4:3", "9:7:4"],
    "correctOption": "D",
    "markscheme": "Original ratio of X and Y is 3:2.\\nZ's share:\\n\\(X\\ gives\\ \\frac{1}{3}\\ of\\ his\\ share = \\frac{1}{3} \\times \\frac{3}{5} = \\frac{1}{5}\\)\\n\\(Y\\ gives\\ \\frac{1}{4}\\ of\\ his\\ share = \\frac{1}{4} \\times \\frac{2}{5} = \\frac{1}{10}\\)\\nTotal share given to Z = \\(\\frac{1}{5} + \\frac{1}{10} = \\frac{2}{10} + \\frac{1}{10} = \\frac{3}{10}\\)\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{3}{5} - \\frac{1}{5} = \\frac{2}{5}\\)\\n\\(Y's\\ new\\ share = \\frac{2}{5} - \\frac{1}{10} = \\frac{4}{10} - \\frac{1}{10} = \\frac{3}{10}\\)\\n\\(Z's\\ share = \\frac{3}{10}\\)\\nNew profit-sharing ratio:\\n\\(X:Y:Z = 2:1.5:1.5\\ which\\ simplifies\\ to\\ 4:3:3\\)."
  },
  {
    "questionId": "501415",
    "text": "P and Q are partners sharing profits and losses in the ratio of 3:2. They admit R into the partnership. P gives 1/4th of his share and Q gives 1/5th of his share to R. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["3:2:1", "7:5:4", "6:4:3", "9:7:4"],
    "correctOption": "B",
    "markscheme": "Original ratio of P and Q is 3:2.\\nR's share:\\n\\(P\\ gives\\ \\frac{1}{4}\\ of\\ his\\ share = \\frac{1}{4} \\times \\frac{3}{5} = \\frac{3}{20}\\)\\n\\(Q\\ gives\\ \\frac{1}{5}\\ of\\ his\\ share = \\frac{1}{5} \\times \\frac{2}{5} = \\frac{2}{25}\\)\\nTotal share given to R = \\(\\frac{3}{20} + \\frac{2}{25} = \\frac{75 + 40}{500} = \\frac{115}{500}\\)\\nNew ratio:\\n\\(P's\\ new\\ share = \\frac{3}{5} - \\frac{3}{20} = \\frac{12}{20} - \\frac{3}{20} = \\frac{9}{20}\\)\\n\\(Q's\\ new\\ share = \\frac{2}{5} - \\frac{2}{25} = \\frac{10}{25} - \\frac{2}{25} = \\frac{8}{25}\\)\\n\\(R's\\ share = \\frac{115}{500}\\)\\nNew profit-sharing ratio:\\n\\(P:Q:R = 9:5:2\\ which\\ simplifies\\ to\\ 7:5:4\\)."
  },
  {
    "questionId": "501416",
    "text": "X and Y are partners sharing profits in the ratio of 3:2. They admit Z into the partnership for 1/5th share in profits. Z acquires his share equally from X and Y. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["3:2:1", "7:5:4", "6:4:3", "9:7:4"],
    "correctOption": "C",
    "markscheme": "Original ratio of X and Y is 3:2.\\nZ's share is 1/5th, and he acquires it equally from X and Y, so each gives up \\(\\frac{1}{10}\\).\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{3}{5} - \\frac{1}{10} = \\frac{6}{10} - \\frac{1}{10} = \\frac{5}{10}\\)\\n\\(Y's\\ new\\ share = \\frac{2}{5} - \\frac{1}{10} = \\frac{4}{10} - \\frac{1}{10} = \\frac{3}{10}\\)\\n\\(Z's\\ share = \\frac{1}{5} = \\frac{2}{10}\\)\\nNew profit-sharing ratio is 6:4:3."
  },
  {
    "questionId": "501417",
    "text": "A, B, and C are partners sharing profits and losses in the ratio of 3:2:1. They admit D into the partnership for 1/6th share in profits. D acquires his share from A, B, and C in the ratio of 2:1:1. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["3:2:1:1", "5:3:2:1", "5:3:2:1", "6:4:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of A, B, and C is 3:2:1.\\nD's share is 1/6th, and he acquires it from A, B, and C in the ratio of 2:1:1.\\nNew ratio:\\n\\(A's\\ new\\ share = \\frac{3}{6} - \\frac{2}{6} = \\frac{1}{6}\\)\\n\\(B's\\ new\\ share = \\frac{2}{6} - \\frac{1}{6} = \\frac{1}{6}\\)\\n\\(C's\\ new\\ share = \\frac{1}{6} - \\frac{1}{6} = \\frac{1}{6}\\)\\n\\(D's\\ share = \\frac{1}{6}\\)\\nNew profit-sharing ratio is 5:3:2:1."
  },
  {
    "questionId": "501418",
    "text": "X, Y, and Z are partners sharing profits in the ratio of 4:3:2. They admit W into the partnership for 1/10th share in profits. W acquires his share equally from X, Y, and Z. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["3:2:1:1", "4:3:2:1", "5:3:2:1", "6:4:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of X, Y, and Z is 4:3:2.\\nW's share is 1/10th, and he acquires it equally from X, Y, and Z.\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{4}{9} - \\frac{1}{30} = \\frac{40}{90} - \\frac{3}{90} = \\frac{37}{90}\\)\\n\\(Y's\\ new\\ share = \\frac{3}{9} - \\frac{1}{30} = \\frac{30}{90} - \\frac{3}{90} = \\frac{27}{90}\\)\\n\\(Z's\\ new\\ share = \\frac{2}{9} - \\frac{1}{30} = \\frac{20}{90} - \\frac{3}{90} = \\frac{17}{90}\\)\\n\\(W's\\ share = \\frac{1}{10} = \\frac{9}{90}\\)\\nNew profit-sharing ratio is 4:3:2:1."
  },
  {
    "questionId": "501419",
    "text": "X, Y, and Z are partners sharing profits in the ratio of 5:4:1. They admit W into the partnership for 1/12th share in profits. W acquires his share from X and Y in the ratio of 2:1. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["5:4:1:1", "6:5:2:1", "6:4:3:1", "7:5:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of X, Y, and Z is 5:4:1.\\nW's share is 1/12th, and he acquires it from X and Y in the ratio of 2:1.\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{5}{10} - \\frac{2}{12} = \\frac{60}{120} - \\frac{20}{120} = \\frac{40}{120}\\)\\n\\(Y's\\ new\\ share = \\frac{4}{10} - \\frac{1}{12} = \\frac{48}{120} - \\frac{10}{120} = \\frac{38}{120}\\)\\n\\(Z's\\ new\\ share = \\frac{1}{10}\\)\\n\\(W's\\ share = \\frac{1}{12}\\)\\nNew profit-sharing ratio is 6:5:2:1."
  },
  {
    "questionId": "501420",
    "text": "Ram and Shyam are partners sharing profits in the ratio of 2:1. They admit Mohan into the partnership for 1/3rd share in profits. Mohan acquires his share from Ram and Shyam in the ratio of 3:1. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["2:1:1", "3:2:1", "3:1:2", "4:2:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of Ram and Shyam is 2:1.\\nMohan's share is 1/3rd, and he acquires it from Ram and Shyam in the ratio of 3:1.\\nNew ratio:\\n\\(Ram's\\ new\\ share = \\frac{2}{3} - \\frac{3}{12} = \\frac{8}{12} - \\frac{3}{12} = \\frac{5}{12}\\)\\n\\(Shyam's\\ new\\ share = \\frac{1}{3} - \\frac{1}{12} = \\frac{4}{12} - \\frac{1}{12} = \\frac{3}{12}\\)\\n\\(Mohan's\\ share = \\frac{1}{3} = \\frac{4}{12}\\)\\nNew profit-sharing ratio is 3:2:1."
  },
  {
    "questionId": "501421",
    "text": "A and B are partners sharing profits and losses in the ratio of 5:3. They admit C into the partnership for 1/4th share in profits. C acquires his share from A and B equally. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["5:3:2", "6:4:3", "4:3:2", "7:5:4"],
    "correctOption": "C",
    "markscheme": "Original ratio of A and B is 5:3.\\nC's share is 1/4th, and he acquires it equally from A and B.\\nNew ratio:\\n\\(A's\\ new\\ share = \\frac{5}{8} - \\frac{1}{8} = \\frac{4}{8}\\)\\n\\(B's\\ new\\ share = \\frac{3}{8} - \\frac{1}{8} = \\frac{2}{8}\\)\\n\\(C's\\ share = \\frac{1}{5} = \\frac{2}{8}\\)\\nNew profit-sharing ratio is 6:4:3."
  },
  {
    "questionId": "501422",
    "text": "X, Y, and Z are partners sharing profits in the ratio of 3:2:1. They admit W into the partnership for 1/5th share in profits. W acquires his share from X, Y, and Z in the ratio of 2:2:1. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["3:2:1:1", "4:3:2:1", "5:3:2:1", "6:4:3:1"],
    "correctOption": "C",
    "markscheme": "Original ratio of X, Y, and Z is 3:2:1.\\nW's share is 1/5th, and he acquires it from X, Y, and Z in the ratio of 2:2:1.\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{3}{6} - \\frac{2}{6} = \\frac{1}{6}\\)\\n\\(Y's\\ new\\ share = \\frac{2}{6} - \\frac{2}{6} = \\frac{0}{6}\\)\\n\\(Z's\\ new\\ share = \\frac{1}{6} - \\frac{1}{6} = \\frac{0}{6}\\)\\n\\(W's\\ share = \\frac{1}{5}\\)\\nNew profit-sharing ratio is 5:3:2:1."
  },
  {
    "questionId": "501423",
    "text": "P, Q, and R are partners sharing profits in the ratio of 4:3:2. They admit S into the partnership for 1/9th share in profits. S acquires his share from P, Q, and R in the ratio of 2:2:1. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["4:3:2:1", "5:4:3:1", "5:3:2:1", "6:4:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of P, Q, and R is 4:3:2.\\nS's share is 1/9th, and he acquires it from P, Q, and R in the ratio of 2:2:1.\\nNew ratio:\\n\\(P's\\ new\\ share = \\frac{4}{9} - \\frac{2}{9} = \\frac{2}{9}\\)\\n\\(Q's\\ new\\ share = \\frac{3}{9} - \\frac{2}{9} = \\frac{1}{9}\\)\\n\\(R's\\ new\\ share = \\frac{2}{9} - \\frac{1}{9} = \\frac{1}{9}\\)\\n\\(S's\\ share = \\frac{1}{9}\\)\\nNew profit-sharing ratio is 5:4:3:1."
  },
  {
    "questionId": "501424",
    "text": "Ram, Mohan, and Sohan are partners sharing profits and losses in the ratio of 5:4:1. They admit Ravi into the partnership for 1/12th share in profits. Ravi acquires his share from Ram and Mohan in the ratio of 3:1. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["5:4:1:1", "6:5:2:1", "6:4:3:1", "7:5:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of Ram, Mohan, and Sohan is 5:4:1.\\nRavi's share is 1/12th, and he acquires it from Ram and Mohan in the ratio of 3:1.\\nNew ratio:\\n\\(Ram's\\ new\\ share = \\frac{5}{10} - \\frac{3}{12} = \\frac{60}{120} - \\frac{20}{120} = \\frac{40}{120}\\)\\n\\(Mohan's\\ new\\ share = \\frac{4}{10} - \\frac{1}{12} = \\frac{48}{120} - \\frac{10}{120} = \\frac{38}{120}\\)\\n\\(Sohan's\\ new\\ share = \\frac{1}{10}\\)\\n\\(Ravi's\\ share = \\frac{1}{12}\\)\\nNew profit-sharing ratio is 6:5:2:1."
  },
  {
    "questionId": "501425",
    "text": "X, Y, and Z are partners sharing profits in the ratio of 3:2:1. They admit W into the partnership for 1/6th share in profits. W acquires his share equally from X and Y. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["3:2:1:1", "4:3:2:1", "5:3:2:1", "6:4:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of X, Y, and Z is 3:2:1.\\nW's share is 1/6th, and he acquires it equally from X and Y.\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{3}{6} - \\frac{1}{12} = \\frac{6}{12} - \\frac{1}{12} = \\frac{5}{12}\\)\\n\\(Y's\\ new\\ share = \\frac{2}{6} - \\frac{1}{12} = \\frac{4}{12} - \\frac{1}{12} = \\frac{3}{12}\\)\\n\\(Z's\\ new\\ share = \\frac{1}{6} = \\frac{2}{12}\\)\\n\\(W's\\ share = \\frac{1}{6} = \\frac{2}{12}\\)\\nNew profit-sharing ratio is 4:3:2:1."
  },
  {
    "questionId": "501426",
    "text": "A and B are partners sharing profits and losses in the ratio of 5:3. They admit C into the partnership for 1/5th share in profits. C acquires his share from A and B equally. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["5:3:2", "6:4:3", "4:3:2", "7:5:4"],
    "correctOption": "C",
    "markscheme": "Original ratio of A and B is 5:3.\\nC's share is 1/5th, and he acquires it equally from A and B.\\nNew ratio:\\n\\(A's\\ new\\ share = \\frac{5}{8} - \\frac{1}{8} = \\frac{4}{8}\\)\\n\\(B's\\ new\\ share = \\frac{3}{8} - \\frac{1}{8} = \\frac{2}{8}\\)\\n\\(C's\\ share = \\frac{1}{5} = \\frac{2}{8}\\)\\nNew profit-sharing ratio is 6:4:3."
  },
  {
    "questionId": "501427",
    "text": "Ram, Shyam, and Mohan are partners sharing profits in the ratio of 4:3:2. They admit Ravi into the partnership for 1/10th share in profits. Ravi acquires his share equally from Ram, Shyam, and Mohan. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["4:3:2:1", "5:3:2:1", "5:3:2:2", "6:4:3:1"],
    "correctOption": "A",
    "markscheme": "Original ratio of Ram, Shyam, and Mohan is 4:3:2.\\nRavi's share is 1/10th, and he acquires it equally from Ram, Shyam, and Mohan.\\nNew ratio:\\n\\(Ram's\\ new\\ share = \\frac{4}{9} - \\frac{1}{30} = \\frac{40}{90} - \\frac{3}{90} = \\frac{37}{90}\\)\\n\\(Shyam's\\ new\\ share = \\frac{3}{9} - \\frac{1}{30} = \\frac{30}{90} - \\frac{3}{90} = \\frac{27}{90}\\)\\n\\(Mohan's\\ new\\ share = \\frac{2}{9} - \\frac{1}{30} = \\frac{20}{90} - \\frac{3}{90} = \\frac{17}{90}\\)\\n\\(Ravi's\\ share = \\frac{1}{10} = \\frac{9}{90}\\)\\nNew profit-sharing ratio is 4:3:2:1."
  },
  {
    "questionId": "501428",
    "text": "A and B are partners sharing profits and losses in the ratio of 2:1. They admit C into the partnership for 1/3rd share in profits. C acquires his share equally from A and B. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["2:1:1", "3:2:1", "3:1:2", "4:2:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of A and B is 2:1.\\nC's share is 1/3rd, and he acquires it equally from A and B.\\nNew ratio:\\n\\(A's\\ new\\ share = \\frac{2}{3} - \\frac{1}{8} = \\frac{8}{12} - \\frac{3}{12} = \\frac{5}{12}\\)\\n\\(B's\\ new\\ share = \\frac{1}{3} - \\frac{1}{8} = \\frac{4}{12} - \\frac{1}{12} = \\frac{3}{12}\\)\\n\\(C's\\ share = \\frac{1}{3} = \\frac{4}{12}\\)\\nNew profit-sharing ratio is 3:2:1."
  },
  {
    "questionId": "501429",
    "text": "Ram, Mohan, and Sohan are partners sharing profits and losses in the ratio of 5:4:1. They admit Ravi into the partnership for 1/9th share in profits. Ravi acquires his share from Ram and Mohan in the ratio of 2:1. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["5:4:1:1", "6:5:2:1", "6:4:3:1", "7:5:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of Ram, Mohan, and Sohan is 5:4:1.\\nRavi's share is 1/9th, and he acquires it from Ram and Mohan in the ratio of 2:1.\\nNew ratio:\\n\\(Ram's\\ new\\ share = \\frac{5}{10} - \\frac{2}{9} = \\frac{60}{90} - \\frac{20}{90} = \\frac{40}{90}\\)\\n\\(Mohan's\\ new\\ share = \\frac{4}{10} - \\frac{1}{9} = \\frac{48}{90} - \\frac{10}{90} = \\frac{38}{90}\\)\\n\\(Sohan's\\ new\\ share = \\frac{1}{10}\\)\\n\\(Ravi's\\ share = \\frac{1}{9}\\)\\nNew profit-sharing ratio is 6:5:2:1."
  },
  {
    "questionId": "501430",
    "text": "A, B, and C are partners sharing profits and losses in the ratio of 3:2:1. They admit D into the partnership for 1/8th share in profits. D acquires his share equally from A, B, and C. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["3:2:1:1", "4:3:2:1", "5:3:2:1", "6:4:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of A, B, and C is 3:2:1.\\nD's share is 1/8th, and he acquires it equally from A, B, and C.\\nNew ratio:\\n\\(A's\\ new\\ share = \\frac{3}{6} - \\frac{1}{8} = \\frac{6}{8} - \\frac{1}{8} = \\frac{5}{8}\\)\\n\\(B's\\ new\\ share = \\frac{2}{6} - \\frac{1}{8} = \\frac{4}{8} - \\frac{1}{8} = \\frac{3}{8}\\)\\n\\(C's\\ new\\ share = \\frac{1}{6} - \\frac{1}{8} = \\frac{2}{8} - \\frac{1}{8} = \\frac{1}{8}\\)\\n\\(D's\\ share = \\frac{1}{8}\\)\\nNew profit-sharing ratio is 4:3:2:1."
  },
  {
    "questionId": "501431",
    "text": "X, Y, and Z are partners sharing profits in the ratio of 5:4:1. They admit W into the partnership for 1/6th share in profits. W acquires his share from X and Y in the ratio of 2:1. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["5:4:1:1", "6:5:2:1", "6:4:3:1", "7:5:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of X, Y, and Z is 5:4:1.\\nW's share is 1/6th, and he acquires it from X and Y in the ratio of 2:1.\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{5}{10} - \\frac{2}{6} = \\frac{60}{120} - \\frac{20}{120} = \\frac{40}{120}\\)\\n\\(Y's\\ new\\ share = \\frac{4}{10} - \\frac{1}{6} = \\frac{48}{120} - \\frac{10}{120} = \\frac{38}{120}\\)\\n\\(Z's\\ new\\ share = \\frac{1}{10}\\)\\n\\(W's\\ share = \\frac{1}{6}\\)\\nNew profit-sharing ratio is 6:5:2:1."
  },
  {
    "questionId": "501432",
    "text": "Ram and Shyam are partners sharing profits in the ratio of 4:3. They admit Mohan into the partnership for 1/8th share in profits. Mohan acquires his share equally from Ram and Shyam. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["4:3:2", "5:3:2", "5:3:1", "6:4:3"],
    "correctOption": "B",
    "markscheme": "Original ratio of Ram and Shyam is 4:3.\\nMohan's share is 1/8th, and he acquires it equally from Ram and Shyam.\\nNew ratio:\\n\\(Ram's\\ new\\ share = \\frac{4}{7} - \\frac{1}{8} = \\frac{32}{56} - \\frac{7}{56} = \\frac{25}{56}\\)\\n\\(Shyam's\\ new\\ share = \\frac{3}{7} - \\frac{1}{8} = \\frac{24}{56} - \\frac{7}{56} = \\frac{17}{56}\\)\\n\\(Mohan's\\ share = \\frac{1}{8} = \\frac{7}{56}\\)\\nNew profit-sharing ratio is 5:3:2."
  },
  {
    "questionId": "501433",
    "text": "A and B are partners sharing profits and losses in the ratio of 3:2. They admit C into the partnership for 1/4th share in profits. C acquires his share equally from A and B. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["3:2:1", "6:4:3", "4:3:2", "7:5:4"],
    "correctOption": "B",
    "markscheme": "Original ratio of A and B is 3:2.\\nC's share is 1/4th, and he acquires it equally from A and B.\\nNew ratio:\\n\\(A's\\ new\\ share = \\frac{3}{5} - \\frac{1}{8} = \\frac{6}{10} - \\frac{1}{10} = \\frac{5}{10}\\)\\n\\(B's\\ new\\ share = \\frac{2}{5} - \\frac{1}{8} = \\frac{4}{10} - \\frac{1}{10} = \\frac{3}{10}\\)\\n\\(C's\\ share = \\frac{1}{4} = \\frac{2}{8}\\)\\nNew profit-sharing ratio is 6:4:3."
  },
  {
    "questionId": "501434",
    "text": "Ram and Shyam are partners sharing profits in the ratio of 2:1. They admit Mohan into the partnership for 1/4th share in profits. Mohan acquires his share equally from Ram and Shyam. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["2:1:1", "3:2:1", "3:1:2", "4:2:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of Ram and Shyam is 2:1.\\nMohan's share is 1/4th, and he acquires it equally from Ram and Shyam.\\nNew ratio:\\n\\(Ram's\\ new\\ share = \\frac{2}{3} - \\frac{1}{8} = \\frac{8}{12} - \\frac{3}{12} = \\frac{5}{12}\\)\\n\\(Shyam's\\ new\\ share = \\frac{1}{3} - \\frac{1}{8} = \\frac{4}{12} - \\frac{1}{12} = \\frac{3}{12}\\)\\n\\(Mohan's\\ share = \\frac{1}{3} = \\frac{4}{12}\\)\\nNew profit-sharing ratio is 3:2:1."
  },
  {
    "questionId": "501435",
    "text": "A, B, and C are partners sharing profits and losses in the ratio of 5:3:2. They admit D into the partnership for 1/5th share in profits. D acquires his share equally from A, B, and C. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["5:3:2:1", "6:4:3:1", "4:3:2:1", "7:5:4:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of A, B, and C is 5:3:2.\\nD's share is 1/5th, and he acquires it equally from A, B, and C.\\nNew ratio:\\n\\(A's\\ new\\ share = \\frac{5}{7} - \\frac{1}{5} = \\frac{25}{35} - \\frac{7}{35} = \\frac{18}{35}\\)\\n\\(B's\\ new\\ share = \\frac{3}{7} - \\frac{1}{5} = \\frac{15}{35} - \\frac{7}{35} = \\frac{8}{35}\\)\\n\\(C's\\ new\\ share = \\frac{2}{7} - \\frac{1}{5} = \\frac{10}{35} - \\frac{7}{35} = \\frac{3}{35}\\)\\n\\(D's\\ share = \\frac{1}{5}\\)\\nNew profit-sharing ratio is 6:4:3:1."
  },
  {
    "questionId": "501436",
    "text": "X, Y, and Z are partners sharing profits in the ratio of 3:2:1. They admit W into the partnership for 1/8th share in profits. W acquires his share equally from X and Y. The new profit-sharing ratio will be:",
    "subject": "Accountancy/Book Keeping",
    "difficulty": "Medium",
    "type": "Multiple Choice",
    "year": "2022",
    "reviewed": false,
    "completed": false,
    "options": ["3:2:1:1", "4:3:2:1", "5:3:2:1", "6:4:3:1"],
    "correctOption": "B",
    "markscheme": "Original ratio of X, Y, and Z is 3:2:1.\\nW's share is 1/8th, and he acquires it equally from X and Y.\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{3}{6} - \\frac{1}{12} = \\frac{6}{12} - \\frac{1}{12} = \\frac{5}{12}\\)\\n\\(Y's\\ new\\ share = \\frac{2}{6} - \\frac{1}{12} = \\frac{4}{12} - \\frac{1}{12} = \\frac{3}{12}\\)\\n\\(Z's\\ new\\ share = \\frac{1}{6} = \\frac{2}{12}\\)\\n\\(W's\\ share = \\frac{1}{6} = \\frac{2}{12}\\)\\nNew profit-sharing ratio is 4:3:2:1."
  },

  {
      "questionId": "501437",
      "text": "Ram and Shyam are partners sharing profits in the ratio of 5:4. They admit Mohan into the partnership for 1/7th share in profits. Mohan acquires his share equally from Ram and Shyam. The new profit-sharing ratio will be:",
      "subject": "Accountancy/Book Keeping",
      "difficulty": "Medium",
      "type": "Multiple Choice",
      "year": "2022",
      "reviewed": false,
      "completed": false,
      "options": ["5:4:2", "6:5:2", "5:3:1", "7:5:3"],
      "correctOption": "B",
      "markscheme": "Original ratio of Ram and Shyam is 5:4.\\nMohan's share is 1/7th, and he acquires it equally from Ram and Shyam.\\nNew ratio:\\n\\(Ram's\\ new\\ share = \\frac{5}{9} - \\frac{1}{7} = \\frac{35}{63} - \\frac{9}{63} = \\frac{26}{63}\\)\\n\\(Shyam's\\ new\\ share = \\frac{4}{9} - \\frac{1}{7} = \\frac{28}{63} - \\frac{9}{63} = \\frac{19}{63}\\)\\n\\(Mohan's\\ share = \\frac{1}{7} = \\frac{9}{63}\\)\\nNew profit-sharing ratio is 6:5:2."
    },
    {
      "questionId": "501438",
      "text": "X, Y, and Z are partners sharing profits in the ratio of 4:3:2. They admit W into the partnership for 1/7th share in profits. W acquires his share equally from X, Y, and Z. The new profit-sharing ratio will be:",
      "subject": "Accountancy/Book Keeping",
      "difficulty": "Medium",
      "type": "Multiple Choice",
      "year": "2022",
      "reviewed": false,
      "completed": false,
      "options": ["4:3:2:1", "5:3:2:1", "5:3:2:2", "6:4:3:1"],
      "correctOption": "A",
      "markscheme": "Original ratio of X, Y, and Z is 4:3:2.\\nW's share is 1/7th, and he acquires it equally from X, Y, and Z.\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{4}{9} - \\frac{1}{7} = \\frac{28}{63} - \\frac{9}{63} = \\frac{19}{63}\\)\\n\\(Y's\\ new\\ share = \\frac{3}{9} - \\frac{1}{7} = \\frac{21}{63} - \\frac{9}{63} = \\frac{12}{63}\\)\\n\\(Z's\\ new\\ share = \\frac{2}{9} - \\frac{1}{7} = \\frac{14}{63} - \\frac{9}{63} = \\frac{5}{63}\\)\\n\\(W's\\ share = \\frac{1}{7} = \\frac{9}{63}\\)\\nNew profit-sharing ratio is 4:3:2:1."
    },
    {
      "questionId": "501439",
      "text": "Ram, Mohan, and Sohan are partners sharing profits and losses in the ratio of 5:4:1. They admit Ravi into the partnership for 1/6th share in profits. Ravi acquires his share equally from Ram and Mohan. The new profit-sharing ratio will be:",
      "subject": "Accountancy/Book Keeping",
      "difficulty": "Medium",
      "type": "Multiple Choice",
      "year": "2022",
      "reviewed": false,
      "completed": false,
      "options": ["5:4:1:1", "6:5:2:1", "6:4:3:1", "7:5:3:1"],
      "correctOption": "B",
      "markscheme": "Original ratio of Ram, Mohan, and Sohan is 5:4:1.\\nRavi's share is 1/6th, and he acquires it equally from Ram and Mohan.\\nNew ratio:\\n\\(Ram's\\ new\\ share = \\frac{5}{10} - \\frac{1}{6} = \\frac{60}{120} - \\frac{20}{120} = \\frac{40}{120}\\)\\n\\(Mohan's\\ new\\ share = \\frac{4}{10} - \\frac{1}{6} = \\frac{48}{120} - \\frac{10}{120} = \\frac{38}{120}\\)\\n\\(Sohan's\\ new\\ share = \\frac{1}{10}\\)\\n\\(Ravi's\\ share = \\frac{1}{6}\\)\\nNew profit-sharing ratio is 6:5:2:1."
    },
    {
      "questionId": "501440",
      "text": "X, Y, and Z are partners sharing profits in the ratio of 4:3:2. They admit W into the partnership for 1/10th share in profits. W acquires his share equally from X, Y, and Z. The new profit-sharing ratio will be:",
      "subject": "Accountancy/Book Keeping",
      "difficulty": "Medium",
      "type": "Multiple Choice",
      "year": "2022",
      "reviewed": false,
      "completed": false,
      "options": ["4:3:2:1", "5:3:2:1", "5:3:2:2", "6:4:3:1"],
      "correctOption": "A",
      "markscheme": "Original ratio of X, Y, and Z is 4:3:2.\\nW's share is 1/10th, and he acquires it equally from X, Y, and Z.\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{4}{7} - \\frac{1}{10} = \\frac{40}{70} - \\frac{10}{70} = \\frac{30}{70}\\)\\n\\(Y's\\ new\\ share = \\frac{3}{7} - \\frac{1}{10} = \\frac{30}{70} - \\frac{10}{70} = \\frac{20}{70}\\)\\n\\(Z's\\ new\\ share = \\frac{2}{7} - \\frac{1}{10} = \\frac{20}{70} - \\frac{10}{70} = \\frac{10}{70}\\)\\n\\(W's\\ share = \\frac{1}{10} = \\frac{10}{70}\\)\\nNew profit-sharing ratio is 4:3:2:1."
    },
    {
      "questionId": "501441",
      "text": "Ram, Shyam, and Mohan are partners sharing profits and losses in the ratio of 3:2:1. They admit Ravi into the partnership for 1/8th share in profits. Ravi acquires his share from Ram, Shyam, and Mohan in the ratio of 2:1:1. The new profit-sharing ratio will be:",
      "subject": "Accountancy/Book Keeping",
      "difficulty": "Medium",
      "type": "Multiple Choice",
      "year": "2022",
      "reviewed": false,
      "completed": false,
      "options": ["3:2:1:1", "4:3:2:1", "5:3:2:1", "6:4:3:1"],
      "correctOption": "C",
      "markscheme": "Original ratio of Ram, Shyam, and Mohan is 3:2:1.\\nRavi's share is 1/8th, and he acquires it from Ram, Shyam, and Mohan in the ratio of 2:1:1.\\nNew ratio:\\n\\(Ram's\\ new\\ share = \\frac{3}{6} - \\frac{2}{8} = \\frac{6}{8} - \\frac{2}{8} = \\frac{4}{8}\\)\\n\\(Shyam's\\ new\\ share = \\frac{2}{6} - \\frac{1}{8} = \\frac{4}{8} - \\frac{1}{8} = \\frac{3}{8}\\)\\n\\(Mohan's\\ new\\ share = \\frac{1}{6} - \\frac{1}{8} = \\frac{2}{8} - \\frac{1}{8} = \\frac{1}{8}\\)\\n\\(Ravi's\\ share = \\frac{1}{8}\\)\\nNew profit-sharing ratio is 5:3:2:1."
    },
    {
      "questionId": "501442",
      "text": "A, B, and C are partners sharing profits and losses in the ratio of 5:4:1. They admit D into the partnership for 1/7th share in profits. D acquires his share from A, B, and C in the ratio of 2:2:1. The new profit-sharing ratio will be:",
      "subject": "Accountancy/Book Keeping",
      "difficulty": "Medium",
      "type": "Multiple Choice",
      "year": "2022",
      "reviewed": false,
      "completed": false,
      "options": ["5:4:1:1", "6:5:2:1", "6:4:3:1", "7:5:3:1"],
      "correctOption": "B",
      "markscheme": "Original ratio of A, B, and C is 5:4:1.\\nD's share is 1/7th, and he acquires it from A, B, and C in the ratio of 2:2:1.\\nNew ratio:\\n\\(A's\\ new\\ share = \\frac{5}{10} - \\frac{2}{7} = \\frac{60}{70} - \\frac{20}{70} = \\frac{40}{70}\\)\\n\\(B's\\ new\\ share = \\frac{4}{10} - \\frac{2}{7} = \\frac{48}{70} - \\frac{20}{70} = \\frac{28}{70}\\)\\n\\(C's\\ new\\ share = \\frac{1}{10}\\)\\n\\(D's\\ share = \\frac{1}{7}\\)\\nNew profit-sharing ratio is 6:5:2:1."
    },
    {
      "questionId": "501443",
      "text": "X, Y, and Z are partners sharing profits in the ratio of 5:3:2. They admit W into the partnership for 1/8th share in profits. W acquires his share equally from X, Y, and Z. The new profit-sharing ratio will be:",
      "subject": "Accountancy/Book Keeping",
      "difficulty": "Medium",
      "type": "Multiple Choice",
      "year": "2022",
      "reviewed": false,
      "completed": false,
      "options": ["5:3:2:1", "6:5:2:1", "5:3:2:2", "6:4:3:1"],
      "correctOption": "A",
      "markscheme": "Original ratio of X, Y, and Z is 5:3:2.\\nW's share is 1/8th, and he acquires it equally from X, Y, and Z.\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{5}{6} - \\frac{1}{8} = \\frac{40}{48} - \\frac{6}{48} = \\frac{34}{48}\\)\\n\\(Y's\\ new\\ share = \\frac{3}{6} - \\frac{1}{8} = \\frac{24}{48} - \\frac{6}{48} = \\frac{18}{48}\\)\\n\\(Z's\\ new\\ share = \\frac{2}{6} - \\frac{1}{8} = \\frac{16}{48} - \\frac{6}{48} = \\frac{10}{48}\\)\\n\\(W's\\ share = \\frac{1}{8}\\)\\nNew profit-sharing ratio is 5:3:2:1."
    },
    {
      "questionId": "501444",
      "text": "Ram and Shyam are partners sharing profits in the ratio of 3:2. They admit Mohan into the partnership for 1/9th share in profits. Mohan acquires his share equally from Ram and Shyam. The new profit-sharing ratio will be:",
      "subject": "Accountancy/Book Keeping",
      "difficulty": "Medium",
      "type": "Multiple Choice",
      "year": "2022",
      "reviewed": false,
      "completed": false,
      "options": ["3:2:1", "4:3:1", "4:3:2", "5:3:2"],
      "correctOption": "B",
      "markscheme": "Original ratio of Ram and Shyam is 3:2.\\nMohan's share is 1/9th, and he acquires it equally from Ram and Shyam.\\nNew ratio:\\n\\(Ram's\\ new\\ share = \\frac{3}{5} - \\frac{1}{9} = \\frac{27}{45} - \\frac{5}{45} = \\frac{22}{45}\\)\\n\\(Shyam's\\ new\\ share = \\frac{2}{5} - \\frac{1}{9} = \\frac{18}{45} - \\frac{5}{45} = \\frac{13}{45}\\)\\n\\(Mohan's\\ share = \\frac{1}{9}\\)\\nNew profit-sharing ratio is 4:3:1."
    },
    {
      "questionId": "501445",
      "text": "X, Y, and Z are partners sharing profits in the ratio of 4:3:2. They admit W into the partnership for 1/7th share in profits. W acquires his share equally from X, Y, and Z. The new profit-sharing ratio will be:",
      "subject": "Accountancy/Book Keeping",
      "difficulty": "Medium",
      "type": "Multiple Choice",
      "year": "2022",
      "reviewed": false,
      "completed": false,
      "options": ["4:3:2:1", "5:3:2:1", "5:3:2:2", "6:4:3:1"],
      "correctOption": "A",
      "markscheme": "Original ratio of X, Y, and Z is 4:3:2.\\nW's share is 1/7th, and he acquires it equally from X, Y, and Z.\\nNew ratio:\\n\\(X's\\ new\\ share = \\frac{4}{7} - \\frac{1}{7} = \\frac{3}{7}\\)\\n\\(Y's\\ new\\ share = \\frac{3}{7} - \\frac{1}{7} = \\frac{2}{7}\\)\\n\\(Z's\\ new\\ share = \\frac{2}{7} - \\frac{1}{7} = \\frac{1}{7}\\)\\n\\(W's\\ share = \\frac{1}{7}\\)\\nNew profit-sharing ratio is 4:3:2:1."
    }

  ];

async function main() {
  for (const question of questions) {
    await prisma.question.create({
      data: {
        questionId: question.questionId,
        text: question.text,
        subject: question.subject,
        difficulty: question.difficulty,
        type: question.type,
        year: parseInt(question.year, 10),
        reviewed: question.reviewed,
        completed: question.completed,
        options: question.options,
        correctOption: question.correctOption,
        markscheme: question.markscheme,
      },
    });
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
